### ISSUE TITLE
Research Gas Cost Implications with Berlin Hardfork for Peggy

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#1038]
The Berlin hard fork is coming to ethereum mainnet on April the 14th. With it, there are changes to SLOAD and CALLDATA opcodes that could directly impact how much gas peggy is spending. Because of this, we need to figure out what the new costs are going to be for our smart contracts to run on mainnet. If gas prices are going to change drastically for us, we may need to do a hot fix to the smart contracts to remove as much reading and writing to storage as we possibly can.

**Comment by ElliotFriedman** [comment]
Current findings:
We will be charged approximately 30K more gas than we are currently paying on mainnet with the changes in the berlin hardfork when unpegging ERC20 tokens from sifchain to ethereum. 

Pegging rowan from sifchain to ethereum will cost approximately 50k more gas.

https://docs.google.com/spreadsheets/d/1aRVVgCpr9_u7WD8RLXHjRM8J0JnSalFRP3WdLUJzIlU/edit#gid=0

**Comment by pandaring2you** [comment]
Note: 50K gas increase for unpegging (10-20% increase in gas costs)

Should we optimize current smart contracts, even though changes will be moot when we go to Peggy 2.0? 
AI: Jordan - check in with Jazear on this

**Comment by ElliotFriedman** [comment]
@pandaring2you I have some gas optimizations prepped on this PR. These changes will need to go out for review and we will need to test them in their own environment and then move them through the pipeline.

Currently, I have been able to save 54,283 gas on unlocking tokens and 36,805 gas on pegging rowan to erowan.

This will require some coordination to upgrade these smart contracts in production, however, we can get all auditors to sign off, run through the process in dev and testnet to upgrade them as a dry run, and then do a live upgrade before Berlin.

PR: https://github.com/Sifchain/sifnode/pull/1041

**Comment by ElliotFriedman** [comment]
Berlin Links:
https://www.reddit.com/r/ethereum/comments/m0laoy/ethereum_berlin_upgrade_announcement/
https://eips.ethereum.org/EIPS/eip-2929

**Comment by ElliotFriedman** [comment]
We will not be going forward with optimizations at this time.
