### ISSUE TITLE
Onboarding Task for Dev or Technical PM/EM (Marshall)

### ISSUE THREAD

**Issue by caseyturnerarrington** [Sifchain/sifnode#1090]
Read the following documents:
- [x] [Liquidity Pool PRD](https://docs.google.com/document/u/1/d/1P9Co01zrTFz-x9ardaoYF7xfVskN21XR/edit)
- [x] Peggy Review: [Peggy Integration PRD](https://docs.google.com/document/d/1sOg5CKW6tm8YMB0hBh8OGmOIX7eJpxBY/edit#heading=h.7n7c55dtc44q), [Peggy Architecture (no IBC)](https://github.com/Sifchain/peggy/blob/develop/docs/sifchain-peggy-architecture-no-ibc.md), [Peggy ADR describing temporary Sifnode integration](https://github.com/Sifchain/sifnode/blob/3314db7e7dd49339061c6ab1ac4cb25f2aafe7b3/docs/adr-001-peggy-with-sifnode.md)
- [x] Review Cosmos SDK intro docs as needed: https://docs.cosmos.network/
- [x] Review list of available Cosmos modules: https://docs.cosmos.network/master/modules/

Coding Work:
- [ ] Deploy a node to the Sifchain Public Testnet - https://github.com/Sifchain/sifnode
- [x] Complete all four tutorials: https://tutorials.cosmos.network/

**Comment by marshsif** [comment]
I've gone through everything above. Getting a sifnode deployed proved difficult because the docs don't cover AWS EKS setup for k8s or for standalone config. I'll chat with Brent and Grant about it on Monday.
