### ISSUE TITLE
.42 upgrade: Dispensation Module

### ISSUE THREAD

**Issue by iverc** [Sifchain/sifnode#1102]

**Comment by marshsif** [comment]
Based on a convo yesterday, I'm reassigning this to Tanmay, who won't be able to start work on this until next week.

**Comment by timlind** [comment]
Fyi this task's title is technically done in the last ebrelayer PR, so should probably change. The remaining work is to migrate new dispensation work on top of that.

**Comment by kingpinXD** [comment]
@timlind @marshsif  , Yup Tim is correct . My work would go on top of the work he already did .

**Comment by marshsif** [comment]
ok thanks

**Comment by marshsif** [comment]
Tanmay, from the above comments, I'm not clear on the scope of the work for dispensation, can you briefly explain?

**Comment by marshsif** [comment]
@intl-man PR 1159, which relates to this ticket, outlines some genesis state work for deployment. Not sure how we should record & track these downstream tasks so that we don't overlook them?

**Comment by marshsif** [comment]
PR 1234 is for work in .42. 
PR 1146 shows the same work that was done for .39. 
PR 1159 adds genesis state export to .39

**Comment by Jedi2002** [comment]
This work has been done ,and the complete code should be available in  feature/cosmos-grpc-dispensation  branch
