### ISSUE TITLE
Liquidity Event Typo

### ISSUE THREAD

**Issue by AustinoBombino** [Sifchain/sifnode#1200]
**Current behavior**
Liquidity Provider events reported from Sifnode have a typo in the liquidity_provider attribute:
 ```
 "key": "liquidity_provider",
 "value": "ExternalAsset: Symbol: cusdt\n\tLiquidityProviderUnits: 193435784477519469\n\tliquidityOroviderAddress: sif1k3ldrhrtkr6ncgjlu2ltyls9rxqtu9643lknrk"
              }
```

**Expected behavior**
liquidityOroviderAddress should be liquidityProviderAddress

**Additional context**
Typo is here in code:
https://github.com/Sifchain/sifnode/blob/5932be4dc63656f5e011bb88e359810af8238722/x/clp/types/types.go#L52

**Comment by caseyturnerarrington** [comment]
@AustinoBombino are you planning on taking this on this sprint?

**Comment by AustinoBombino** [comment]
@caseyturnerarrington yeah I can knock this out

**Comment by caseyturnerarrington** [comment]
@AustinoBombino are you still planning on getting to this before Tuesday?

**Comment by AustinoBombino** [comment]
@caseyturnerarrington Yup, ready for review.

**Comment by AustinoBombino** [comment]
@caseyturnerarrington @marshsif 
Review for this PR is done, just need someone with merge permissions.
