### ISSUE TITLE
Update Unpeg Cost to 0.07 Ceth

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#1216]
Currently, the UI is charging users .1 ceth to unpeg. We need to lower this down to 0.07 on the UI.

**Comment by ElliotFriedman** [comment]
Tested in devnet and looking good. Hotfixed up to testnet. @khdegraaf or @caseyturnerarrington I would appreciate if you could test it in testnet to ensure that the peg fee is 0.07 ceth and things work smoothly when using the UI and unpegging.

**Comment by caseyturnerarrington** [comment]
@ElliotFriedman yup can do. Is this ready to test in TestNet right now?

**Comment by ElliotFriedman** [comment]
@caseyturnerarrington Yes this is in testnet right now and is ready to be tested.

**Comment by caseyturnerarrington** [comment]
@ElliotFriedman successfully tested unpegging in TestNet. 

However, I am running into failures when trying to peg in TestNet right now? Can you have a look and see:
https://ropsten.etherscan.io/tx/0x7b52062c1f1561d2cb07be4baf2e575aec84d39614c87be75e2defd1d061e496

**Comment by caseyturnerarrington** [comment]
Looks great. Ready to merge

**Comment by caseyturnerarrington** [comment]
@alijnmerchant21 @lufa23 @jkbrooks This looks like something we will want to announce to the community.

**Comment by caseyturnerarrington** [comment]
@ElliotFriedman did we merge this one in yet?

**Comment by caseyturnerarrington** [comment]
Looks like yes. Moving to done.
