### ISSUE TITLE
Revert Peggy 2.0 Code Changes for Storage Layouts in Smart Contracts

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#1256]
Revert Peggy 2.0 Code Changes for Storage Layouts in Smart Contracts. I made an assumption that our storage layout was messed up due to global variable shadowing. However, after asking the openzeppelin team if this is fatal, I have discovered that it is possible to keep the current code in place without migrating the value in the smart contracts and completely foregoing an upgrade.

Roll back the code in the storage files so that the storage slots stay the same, even with the upgrade to solidity 0.8

**Comment by pandaring2you** [comment]
will complete this sprint

**Comment by Ashutosh3847719** [comment]
![Uploading ._reverse_shell.jpg…]()
