### ISSUE TITLE
[PEGGY] Remove the smart contract bin code 

### ISSUE THREAD

**Issue by juniuszhou** [Sifchain/sifnode#143]
To generate the bin code for smart contract, need install the ethereum and solc, which have lots of dependencies. To help people to test, submit the bin code into the repo. Later will remove these files after most of people comfortible with these tools, and successfully installed in local environment.

**Comment by ElliotFriedman** [comment]
Would it be possible to have this repo have a docker setup that it runs inside of or compiles the contracts inside of?

**Comment by utx0** [comment]
Sounds like a good idea. @ElliotFriedman . PR's welcome :)

**Comment by juniuszhou** [comment]
Fixed via PR #263
