### ISSUE TITLE
Some transactions do not appear on the blockexplorer 

### ISSUE THREAD

**Issue by lufa23** [Sifchain/sifnode#1464]
A community member claims that there is a bug on block explorer, as he is unable to find some transactions.
For example, he claims that sif18ewu5dcrc92scrmvgh04pe7t0jpnc96yw9fsw4 sent 1 ROWAN to sif1m48ym067g2tsqcxak5qjzs0jdmsuvf9xzy64tz with a memo, and that the transaction happened on May-03-2021 10:00:14 PM +UTC.

I checked on the block explorer, and the transaction does not appear. Interestingly,  similar transaction (between the same addresses, same amount y a memo) happened yesterday, and it is correctly shown in the block explorer.

Can some updates on the block explorer be the reason why the first transaction does not appear in the block explorer, while the last one does? If this was the case, shouldn’t the block explorer be able to fetch the event of the first transaction anyway?

**Comment by caseyturnerarrington** [comment]
Closing. Not supporting BE anymore
