### ISSUE TITLE
Add mapping code to ebrelayer for ibc tokens

### ISSUE THREAD

**Issue by banshee** [Sifchain/sifnode#1505]
We're going to add a bimap to ebrelayer to map between ibc symbols (or any other symbol) and sifchain denoms.  It'll be maintained by hand for the first rev of ibc.

Also update ebrelayer to not do the symbol munging in EthereumEventToEthBridgeClaim where it looks for an 'e' in the symbol and does something special.  We'll do that mapping the relayer so EthereumEventToEthBridgeClaim just gets things like rowan instead of erowan.

**Comment by pandaring2you** [comment]
hey @banshee - do we still want to hold back on this PR until we release .42? or are we merging this in with .42?

**Comment by banshee** [comment]
> hey @banshee - do we still want to hold back on this PR until we release .42? or are we merging this in with .42?

We want to wait and not disturb .42.

**Comment by pandaring2you** [comment]
Dependent on testing team for additional verification. We are assuming that our tests with fake ibc tokens are sufficient.
