### ISSUE TITLE
Investigate Impact of EIP 1559 on Relayers

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1536]
Per Elliot: 
We need to investigate this before EIP-1559 rolls out to determine impact if any on our relayers https://hackmd.io/@q8X_WM2nTfu6nuvAzqXiTQ/1559-wallets

https://blog.ethereum.org/2021/06/18/london-testnets-announcement/

https://static.coindesk.com/wp-content/uploads/2021/06/EIP-1559-Ethereum-Fee-Market-Upgrade-Explained-1.pdf

--------
https://www.coindesk.com/4-myths-about-ethereum-eip-1559
https://www.coindesk.com/ethereum-improvement-proposal-1559-london-hard-fork
https://www.coindesk.com/research/reports/eip-1559-ethereum-upgrade-explained

**Comment by pandaring2you** [comment]
Heya @intl-man - Elliot is out until Monday. The timing of the proposal seems to be some time in July - do you think you can take a look in case we need time to make relayer changes, test, and deploy?

**Comment by pandaring2you** [comment]
Looks like it was launched on ropsten today:

https://blog.ethereum.org/2021/06/18/london-testnets-announcement/

**Comment by pandaring2you** [comment]
Will see if it will work fine on ropsten - sync with Brent to see if any issues after he tests by EOW.

**Comment by pandaring2you** [comment]
Looks like aug 4th is the proposed date: https://github.com/ethereum/eth1.0-specs/pull/223#issuecomment-874903883

**Comment by pandaring2you** [comment]
@intl-man - did you find any issues with eip 1559? aug 4th appears to be the estimated mainnet date

**Comment by pandaring2you** [comment]
Probably okay on this given the testing that's been happening on Ropsten, will check with Brent next week

from Brent: 

Hey Jordan. Good question. Lets try and touch base about this next week... I'll take a look over the weekend, but I believe we should be ok because Ropsten should have upgraded already and we've been pegging in assets on the new testnets without any issues....

**Comment by ElliotFriedman** [comment]
We are going to kick the can on this one down the road as there will be backwards compatibility with the old system. We will upgrade once patterns for dealing with these changes are known.

**Comment by pandaring2you** [comment]
@ElliotFriedman - Just so we're clear - are we sure we wont run into any critical issues when the eip launches on mainnet August 4th? or do we still need to have Brent take a deeper look?

**Comment by ElliotFriedman** [comment]
We should be good as ropsten rolled out EIP1559 and relayers kept functioning normally.
