### ISSUE TITLE
New Prophecy ID

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1544]
Hey Junius - Can you please add a description and time estimate of this task? Thanks
https://github.com/Sifchain/sifnode/pull/1539

**Comment by juniuszhou** [comment]
documentation for new prophecy id as https://docs.google.com/document/d/17mcRRWFrkWp-LcYk5IQc7W_b6f1Q4LCcQg9NnZCRjUc/edit#. the old design for prophecy id and its content is very difficult to understand. so we decide to change it and use the new algorithm in peggy2.0

**Comment by pandaring2you** [comment]
Cool - So sounds like this will eliminate failed transactions due to additional signatures on finalized prophecies and make it easier for relayers to restart.

**Comment by juniuszhou** [comment]
Yes, we will accept all transactions from relayer even the prophecy already finalized. After the implementation, we can easily find out which relayer not send the claim for specific prophecy.

**Comment by pandaring2you** [comment]
Forked from Peg Multiple Network (failed test cases) ETA tomorrow

**Comment by pandaring2you** [comment]
Need one final review from Elliot

**Comment by juniuszhou** [comment]
pr https://github.com/Sifchain/sifnode/pull/1539 merged.
