### ISSUE TITLE
Sifnode changes to emit and increment global nonce based a destination network descriptor (formerly Signature Aggregation)

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1582]
Problem: Transactions are sometimes dropped because of misordering. This means a user doesn't receive their funds on the destination chain during an export. 

Oneliner: In order to ensure that the relayer does not process transactions out of order, it is necessary to order transactions across the bridge to ensure all transactions are processed in order. 

Goals: Reduce operational cost so that there are zero instances of dropped transactions

Tech Specs:
https://docs.google.com/document/d/1-0_k7NsovQ1afGji90eFMf_TRiQSsv9KgRYIwP88JIk/edit#heading=h.gjt3dja2mcng

cc @ElliotFriedman

**Comment by Brando753** [comment]
Was moved to in progress a little early, Started work on today 7-19-2021.

**Comment by ElliotFriedman** [comment]
@Brando753 Please let us know the branch you are working off and any questions you have. We want to have tight feedback loops so that we are all on the same page.

**Comment by pandaring2you** [comment]
hand off to Junius as stateless sig aggregation is dependent on this work.

**Comment by juniuszhou** [comment]
https://github.com/Sifchain/sifnode/pull/1639 pr created.

**Comment by pandaring2you** [comment]
Need final check from @ElliotFriedman, then ready for merge to future/peggy2
