### ISSUE TITLE
Modify Sifnode Lock Command: Charge Fees in BNB instead of ETH

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1588]
https://sifchain.aha.io/features/SC-53

**Comment by pandaring2you** [comment]
ETA today

**Comment by pandaring2you** [comment]
One final code review and should be able to merge to future/peggy2 by today.

**Comment by juniuszhou** [comment]
https://github.com/Sifchain/sifnode/pull/1565 merged.
