### ISSUE TITLE
Smart Contract Tooling: Migrate to Hardhat

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1591]
https://sifchain.aha.io/features/SC-78

**Comment by pandaring2you** [comment]
ETA by early next week

**Comment by pandaring2you** [comment]
ETA tomorrow

**Comment by pandaring2you** [comment]
Quick checkin w/Elliot, should be pretty much complete

**Comment by banshee** [comment]
PR: https://github.com/Sifchain/sifnode/pull/1559

**Comment by pandaring2you** [comment]
@ElliotFriedman @banshee to chat about to merge now or later due to eRowan to Rowan changes.
