### ISSUE TITLE
Migrate eRowan to Rowan

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1594]
https://docs.google.com/document/d/1rJzIB8js2DGa7QDHYtmbBxWkaxILC2GRTJw-rWgAY4o/edit

**Comment by ElliotFriedman** [comment]
@banshee Will now take point on integrating this code into the bridgebank.

**Comment by banshee** [comment]
Duplicate of https://github.com/Sifchain/peggy/issues/108, so closing this one.
