### ISSUE TITLE
[PEGGY] What should our peggy threshold be for oracles on ethereum?

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#162]
Currently, peggy only needs a single oracle to sign off on it to release or mint user funds on ethereum. I would like to know how many oracles we are going to have on top of the ethereum side to sign off on a single transaction before we consider it valid.

This is a trivial change in the env file, however, it is something that I need to know in terms of how we want to set up peggy.

**Comment by ElliotFriedman** [comment]
For the testnet version of peggy, there will be 4 validators and we will only require 1 signature at least for the current deployment I am doing. After that, we will have to make a judgement call on what we think is an acceptable amount of validators signing off on transactions.

**Comment by jkbrooks** [comment]
@ElliotFriedman we will need two classes of validators, one that can mint tokens or release tokens on Ethereum and one that can’t.  Until we actually implement cryptoeconomic security, only a Sifchain admin Peggy node can actually mint or release tokens on Ethereum or Cosmos.  @AustinoBombino is working on that now. We will actually need to make a few modifications to Peggy beyond this to reduce control and liability for the bridge operator which we will discuss separately

**Comment by ElliotFriedman** [comment]
@jkbrooks If there are going to be two classes of validators in peggy and one can't mint or release tokens, then what can they do as validators? Will it be a system where the threshold doesn't matter until an admin validator signs off on the transaction?

**Comment by ElliotFriedman** [comment]
The development team got sign off from the executive team for the MVP that 4 validators must sign off on a transaction for it to be approved.

**Comment by utx0** [comment]
I really think we need a 66% setup with peggy validators by the by. ie 3/4 are required for signing. If we make it a 100% system if you a validators drops offline for whatever reason we will have in-effect a network outage of sorts. @musnit @jkbrooks comments?

**Comment by ElliotFriedman** [comment]
I would be fine changing the configuration from 4/4 to 3/4

**Comment by ElliotFriedman** [comment]
This is really just a .env file configuration so we should agree on this, however there aren't any code changes that will need to go along with this.

@jkbrooks @musnit Thoughts on making the peggy threshold 3/4 instead of 4/4 for mainnet so that if one validator goes down things can still run?

**Comment by ElliotFriedman** [comment]
bump @jkbrooks @musnit

It would be good to get some eyes on this and get our threshold confirmed before our alphanet.

**Comment by utx0** [comment]
I think we just go with a 3/4 setup.
