### ISSUE TITLE
Combine BridgeBank and CosmosBridge Into 1 Contract

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#1635]
In order to optimize gas, simplify architecture and remove the need for the bridgeregistry contract, both the CosmosBridge and the Bridgebank should be combined into a single contract.

The code structure needs to be such that we can upgrade the current bridgebank. The way that this needs to happen is by the CosmosBridge inheriting the bridgebank so that the storage offsets do not get messed up.

When this upgrade is complete, we can remove the bridgeregistry from the codebase completely.

This upgrade will need to be tested off a mainnet fork using the actual bridgebank in production. Current bridgebank proxy address: https://etherscan.io/address/0xb5f54ac4466f5ce7e0d8a5cb9fe7b8c0f35b7ba8

The upgrade logic will need to include a permissioned function that only the operator can call to initialize the new CosmosBridge contract to set up the valset whitelist.

**Comment by pandaring2you** [comment]
begin merging contracts, reviewing tests. will delay for now as signature aggregation is higher priority.
