### ISSUE TITLE
(Relayers) Send proper data to sifnode for the metadata module

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1642]
https://docs.google.com/document/d/1DFYQhiSEArzsDlDfL5GgTnjrAwpz7iS81nCkbhZYCX0/edit#

**Comment by Brando753** [comment]
- [ ] Update Protofile to support new metadata and coin hash name
- [ ] Update Relayer to transmit new metadata to Sifnode
- [ ] Update Sifnode ethbridge to support handling new metadata from relayer
I have closed the duplicate ticket #1641 in favor of this ticket, copied over the immediate tasks for this ticket

**Comment by Brando753** [comment]
Current Working branch is feature/coin-metadata-1642

**Comment by pandaring2you** [comment]
@Brando753 to attach PR to task . Should be ready for code review

**Comment by pandaring2you** [comment]
One final review from Elliot, then ready to merge. @pandaring2you create task for integration tests after merge.

**Comment by pandaring2you** [comment]
Merged as part of Metadata Module Ethbridge Extension #1671
