### ISSUE TITLE
Reimplement Import Whitelist

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1646]
As per Peggy <> Exec discussion on 7/26, we're going to reimplement import whitelisting for peggy 2.0 to save time. Only specific tokens will be allowed to be imported into Sifchain from Ethereum and Binance Smart Chain. The plan is to launch the MVP w/a whitelist, then remove the whitelist to allow any token to be imported in later versions. Note: There is also a whitelist for tokens that are allowed to be imported from IBC that has been built by the IBC team. 

Implementation details to be worked out w/Elliot and IBC team

Ethereum Whitelist:
- Same as current peggy 1.0 whitelist

BSC Whitelist:
- TBD

cc @ElliotFriedman

**Comment by daniportugalgit** [comment]
Done in branch future/peggy2chain-id

**Comment by pandaring2you** [comment]
awaiting code review. @pandaring2you - create task for integration testing when merged to future/peggy2

**Comment by daniportugalgit** [comment]
Working on PR comments

**Comment by 59023g** [comment]
cc @mccallofthewild @ajoslin @caseyturnerarrington

**Comment by caseyturnerarrington** [comment]
@pandaring2you would there be additional work here, outside of what we are already doing for whitlisting with Peggy, IBC, and the front end right now?

**Comment by daniportugalgit** [comment]
Commited adjustments according to the code review.
