### ISSUE TITLE
Allow CosmosBridge to Create a New Bridge Token in submitProphecyClaimAggregatedSigs

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#1668]
Our current version of the peggy2.0 cosmos bridge smart contracts rely on validators to call the `createNewBridgeToken` function. We should not rely on this. Instead, we should have logic in the _submitProphecyClaimAggregatedSigs function that checks if we control this bridge token, and if we don't, checks if this is a double peg, and if it is both a double peg and we don't control. the bridge token address that was sent, we deploy a new smart contract exactly the same way as the createNewBridgeToken function does.

Then we will need unit and integration testing on this.

**Comment by daniportugalgit** [comment]
Implemented;
3 new unit tests created and passing;

To do: integration test

Branch: `future/peggy2create-bridge-token` (derived from `future/peggy2chain-id`)

**Comment by daniportugalgit** [comment]
My WSL is not too fond of running a VM (Vagrant/VirtualBox) inside a VM (WSL itself).
For some reason, my pure Ubuntu (dual-boot) can't install Vagrant:
```
$ curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
gpg: invalid key resource URL '/tmp/apt-key-gpghome.3ujfguY2S9/home:manuelschneid3r.asc.gpg'
gpg: keyblock resource '(null)': General error
gpg: key 7721F63BD38B4796: 2 signatures not checked due to missing keys
gpg: key 1488EB46E192A257: 1 signature not checked due to a missing key
gpg: key 1488EB46E192A257: 1 signature not checked due to a missing key
gpg: key 3B4FE6ACC0B21F32: 3 signatures not checked due to missing keys
gpg: key D94AA3F0EFE21092: 3 signatures not checked due to missing keys
gpg: key 871920D1991BC93C: 1 signature not checked due to a missing key
gpg: Total number processed: 7
gpg:       skipped new keys: 7
```

I'm going to figure this out tomorrow.

**Comment by daniportugalgit** [comment]
When trying to build the docker image using `make`:

```
$ export BASEDIR="~/sifchain/repos/sifnode"
$ make sifdocker
make: *** No rule to make target 'sifdocker'.  Stop.
```

**Comment by daniportugalgit** [comment]
Managed to install Vagrant (they probably uploaded the missing keys).

But now, when I run `./start-integration-env.sh`

I get the Truffle error "Could not find suitable configuration file."
So, it's trying to use Truffle, but we are now using Hardhat instead. I think the scripts have not been updated.

**Comment by daniportugalgit** [comment]
I created a truffle-config.js file with the following configuration:

```
module.exports = {
  networks: {
    develop: {
      host: "127.0.0.1",
      port: 7545,
      network_id: "*" // Match any network id
    }
  },
  compilers: {
    solc: {
      version: "0.8.0"
    }
  }
};
```

Now, the command `./start-integration-env.sh` runs, but cannot find the test scripts. I tested both against `future/peggy2create-bridge-token` and `future/peggy2`.

I've seen those tests in `feature/ibc` branch. I believe this migration from Peggy to peggy2 is a work in progress, so test scripts have not been updated and are unavailable in this repo.

**Comment by daniportugalgit** [comment]
Committed to branch `future/peggy2create-bridge-token`.

Before committing, I merged this branch with `future/peggy2` and `future/peggy2chain-id`, so now we have a single PR with all changes from `future/peggy2create-bridge-token` (this task) and `future/peggy2chain-id`.

Tasks included:
1) This one.

2) [Reimplement Import Whitelist#1646](https://app.zenhub.com/workspaces/sifchain-603ed608675da3001744d736/issues/sifchain/sifnode/1646)

3) [Batch prophecy claim: add network descriptor#1664](https://app.zenhub.com/workspaces/sifchain-603ed608675da3001744d736/issues/sifchain/sifnode/1664)

I suggest abandoning [PR #1663](https://github.com/Sifchain/sifnode/pull/1663) in favor of [this PR](https://github.com/Sifchain/sifnode/pull/1682), which already has adjustments according to #1663 PR code review.

**Comment by daniportugalgit** [comment]
Looking into PR comments (code review)

**Comment by pandaring2you** [comment]
PR comments reviewed. Need to test with mainnet. No major issues expected.

**Comment by pandaring2you** [comment]
Refactored test feature. Needs final review and mainnet testing.
