### ISSUE TITLE
Add ZCX, Frax, Frax-share, Terra USD to whitelist/dex

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1675]
Request from Jazear to add these assets after IBC launch:

https://www.coingecko.com/en/coins/frax
https://www.coingecko.com/en/coins/frax-share
https://www.coingecko.com/en/coins/terra-usd

cc @caseyturnerarrington  @ElliotFriedman

**Comment by pandaring2you** [comment]
Awaiting word from BD on our side and FRAX

**Comment by jkbrooks** [comment]
We are fine to add these tokens

**Comment by pandaring2you** [comment]
tokens were added on 9/18
