### ISSUE TITLE
[ChainOps] ABCI Query RPC Endpoint returns an index out of range error.

### ISSUE THREAD

**Issue by intl-man** [Sifchain/sifnode#171]
Description:

When I visit the following RPC endpoint via my web browser:

`http://<node_ip_address>:26657/abci_query?height=1000`)

the following error is logged to STDOUT on the validator:

`index out of range [0] with length 0`

Version:

```
name: sifchain
server_name: sifnoded
client_name: sifnodecli
version: 0.0.1
commit: 62a7d9d2790153c22fda084357993d4a03daf2fc
build_tags: ""
go: go version go1.15.3 linux/amd64
```

Expected Behaviour:

Any out of range or nil pointer exceptions should be handled gracefully, however the node still continues to create and sign blocks (doesn't crash). 

Additional Information:

No existing Tendermint/Cosmos Github issue exists for this problem at present, but it could be something specific to our implementation.

**Comment by utx0** [comment]
Marking this as a P3 as it doesnt acutally break anything... from what we can find?

**Comment by utx0** [comment]
Incorrect usage of the interface as pre https://docs.tendermint.com/master/rpc/#/ABCI/abci_query
