### ISSUE TITLE
`sifnoded add-genesis-clp-admin` command has incorrect description

### ISSUE THREAD

**Issue by wojciech-sif** [Sifchain/sifnode#1716]
**Current behavior**
`sifnode add-genesis-clp-admin --help` gives incorrect output:
```
Add a genesis account to genesis.json. The provided account must specify
the account address or key name and a list of initial coins. If a key name is given,
the address will be looked up in the local Keybase. The list of initial tokens must
contain valid denominations. Accounts may optionally be supplied with vesting parameters.
```

**Expected behavior**
Printing correct description of `add-genesis-clp-admin` command

**Steps to reproduce**
- Run `sifnode add-genesis-clp-admin --help`
- Look at printed description

**Comment by iverc** [comment]
addressed in #1967
