### ISSUE TITLE
Peggy 2.0 development environment Framework

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1743]

**Comment by Brando753** [comment]
Steps to do:
- [ ] Spin up witnesses
- [ ] Spin up Relayer
- [ ] Spin up Ethereum Chain (Hardhat)
- [ ] Spin up Sifnode
- [ ] Deploy smart Contracts
- [ ] Whitelisting the witness and relayers
- [ ] Setting crosschain fee in ethereum denom on sifchain
- [ ] Run Ethereum Transfer integration test

**Comment by pandaring2you** [comment]
focused on integration tests with Jure. a lot of issues dependent on deprecated code. continuing to find issues in dev env

**Comment by pandaring2you** [comment]
debugging ebralyer (not seeing lock messages).

**Comment by pandaring2you** [comment]
setting up devenv is working. now moving on to the actual integration tests.
