### ISSUE TITLE
[ChainOps] Clean up kubes pods on PR merge.

### ISSUE THREAD

**Issue by utx0** [Sifchain/sifnode#183]
Description:

When a feature branch is merged into develop, the k8s namespace needs to be removed from the feature testnet cluster.

Version:

N/A

Expected Behaviour:

That the namespace is deleted from the testnet feature cluster.

Additional Information:

Refer to the deployment workflow [here](https://github.com/Sifchain/sifnode/blob/develop/.github/workflows/feature.yml), for reference.

**Comment by utx0** [comment]
@intl-man has this now been resolvoed?

**Comment by jkbrooks** [comment]
@intl-man  is this still an issue? If so, please file with the standard format from the dev charter. #308 has an example. We can then get it up on Gitcoin

**Comment by utx0** [comment]
this issue has been resolved.
