### ISSUE TITLE
ebrelayer should read symbol_translator.json from chain data

### ISSUE THREAD

**Issue by banshee** [Sifchain/sifnode#1838]
Right now, ebrelayer reads in a json file to get the ibc hash data.  We need to:

1.  Stop using symbol_translator.json.
2.  Get the equivalent data using a sifnode query 

I'm thinking for the first version we just query sifnode every time we need to do a transaction.  Our volume right now is low enough that the extra queries shouldn't matter.

**Comment by banshee** [comment]
This is probably going to involve changing the buildSymbolTranslator function to do a query instead of reading a file, and running buildSymbolTranslator on every query.

**Comment by pandaring2you** [comment]
Will not do. Only affects future ibc tokens being onboarded with peggy 1.0.
