### ISSUE TITLE
Prod tokenregistry issues

### ISSUE THREAD

**Issue by ajoslin** [Sifchain/sifnode#1859]
Few issues with prod registry.

**Remove**:
- ccel
- cceth
- causc
- crenbtc
- chusd
- campl
- crally

**Rename / Fix**
- ccdai (wrong symbol)
  - Update: `{ "base_denom": "cdai", "denom": "cdai" }`
- ccusdc (wrong symbol, wrong decimals)
  -  Update `{ "base_denom": "cusdc", "denom": "cusdc", "decimals": 6 }`

**Comment by AustinoBombino** [comment]
Deregistered:

- ccdai 
- cceth
- ccusdc
- crally
- crenbtc 
- chusd 
- campl

**Comment by AustinoBombino** [comment]
Deregistered:

- ccel
- causc

**Comment by iverc** [comment]
Registered:
- `cust`
