### ISSUE TITLE
Consolidate whitelisting scripts

### ISSUE THREAD

**Issue by daniportugalgit** [Sifchain/sifnode#1905]
The idea is to have one script that solves all the steps needed to Whitelist tokens.
We MAY leave the icons out of this (and add them manually to the json file after running the mega-script)

My notes to self:
COMBINE:
FetchTokenDetails and generateSifnodeWhitelist.js

FetchTokenDetails:
if symbol.contains a space or whatever other things we're looking for just throw a error

Generate the UI stuff
Should be stored here:
https://github.com/Sifchain/sifchain-ui/blob/develop/ui/core/src/config/networks/ethereum/assets.ethereum.mainnet.json

**Comment by pandaring2you** [comment]
need to resolve merge conflicts

**Comment by pandaring2you** [comment]
will review with James
