### ISSUE TITLE
Get Team Pauser/Unpauser Keys

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1909]
Check with execs - who can we give pause/unpause keys?

- Michael
- Daniel
- Junius
- Brandon
- Yves

**Comment by pandaring2you** [comment]
pinged aidan - i'm not sure who can actually issue the keys, but he wants the whole team to have keys
https://sifchain.slack.com/archives/C01DZ17890D/p1632269298254500

**Comment by musnit** [comment]
Anyone that has a key should be able to add new people to the pauser role via etherscan's web ui, right @ElliotFriedman ? can you write up the steps in a few points or small runbook?

@intl-man @banshee do you have a pauser key?

**Comment by pandaring2you** [comment]
The team synced on this again. It turns out that the only person who can revoke a pauser/unpauser's permissions is the pauser/unpauser themselves. This means if someone were to steal a pauser/unpauser's key, they would be able to pause/unpause the contracts in perpetuity. 

So, question for chainops/executives:
1) I'm assuming we want to have some sort of system that allows someone other than the pauser to revoke their permissions. If so, what would this be: decision by consensus/all powerful admin/other structure? And what do we feel is the priority given our current setup and that this will delay peggy 2.0? I'm assuming this is pretty high pri. 
2) We aren't able to tell who are the current pausers/unpausers without taking a few days to investigate - would just be easier to ask you guys: do you both (Aidan/Jazear) have the pauser/unpauser keys? Just trying to get a sense of who currently has permissions so we can reach out to them if something goes wrong today. 

Notes on the hardware wallet question:
3) We want to build the pauser scripts so we can pause the contracts across multiple evm chains easily. It sounds like the added benefit Brandon mentioned is that we would be able to pause the contracts using hardware wallets quicker. This task is currently proposed for the next sprint, but I would imagine we would want to do #1 first.
4) Further, hardware wallets might not cover all the chains we eventually connect to - probably an issue we can kick down the road when we get to it, but just something to consider if we start integrating non-supported chains like HECO.

**Comment by pandaring2you** [comment]
Note: Awaiting answers from executives
