### ISSUE TITLE
1. Initial Peggy 2.0 Integration Test

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1911]
- Test cEth transfer from Sifchain to ethereum and back  
- End to end testing that requires relayers/sifnode/smart contracts to be functioning

Test 1 on https://docs.google.com/spreadsheets/d/1yEoAJaTjUa3sLtrff7ozIrd6qZo5B1WXgIbI1w9eFPQ/edit#gid=0

**Comment by pandaring2you** [comment]
Merging peggy2 into devenv rebase (will need to resolve merge conflicts).

**Comment by pandaring2you** [comment]
then will merge devenv back into future/peggy2

**Comment by pandaring2you** [comment]
current integration test branch: peggy2/integrationtests . james/junius's work merge with peggy2/integrationtests at useful checkpoints.

**Comment by pandaring2you** [comment]
current integration test branch: peggy2/integration-test-restoration

**Comment by pandaring2you** [comment]
tbd which branch to work off w/Junius

**Comment by pandaring2you** [comment]
A lot of unknowns, might not complete in current sprint (Oct17-28)

**Comment by Brando753** [comment]
Pair Session (Daniel, Brandon, Jure, Michael)
- Got Daniel and Jure running the latest version of DevENV
- Fixed the DevENV env address variables to point the correct ROWAN SOURCE address
- Debugged problems with the python test code passing home values incorrectly (incomplete)
- Verified that the ebrelayer correctly sends transaction across the bridge
- Found problem code and created seperate ticket for GetDenom
- Fixed Metadata pulled into ProcessClaim from token registry
- First Pytest test is passing

**Comment by Brando753** [comment]
Pair Session (Michael, Brandon)
- Added python integration tests to launch.json generator of DevENV
- Refactored OutputWriter for DevENV to support python test env variable generation
- Refactored python integration tests to have more functions use native web3 over javascript calls
- Fixed bug in python integration tests to properly create ethereum accounts (both functions)
- Fixed bug in python integration tests in fetching correct ethereum balance
- Fixed bug in python integration tests on setting home dir setting on signing transactions
- Fixed bug in python integration tests in sending lock transactions to sifnode ethbridge module
- Investigate bug in python integration tests where balances are not getting funded with rowan from send_from_sifchain_to_sifchain
