### ISSUE TITLE
Setup Tenderly Alerts

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1913]
Hey Daniel - I just invited you to tenderly w/the developer pro plan. Hoping you can take it from here to setup the necessary alerts. I think the major one was just to warn us when the relayers are low on ETH. Not sure if there are others @ElliotFriedman or @banshee think we need to setup.

**Comment by daniportugalgit** [comment]
Update: they're looking into it.

![Screenshot (6).png](https://images.zenhubusercontent.com/60f729b7b9da54de9e274ec7/c75b00b5-ae18-4d50-8cdc-9ac2e68c71af)

![Screenshot (7).png](https://images.zenhubusercontent.com/60f729b7b9da54de9e274ec7/31f98fd5-0582-41cc-9ab1-0b9c295befe7)

**Comment by daniportugalgit** [comment]
Done.
![tenderly.PNG](https://images.zenhubusercontent.com/60f729b7b9da54de9e274ec7/8d4c0d7a-96c8-4b67-89ee-f0531102e77c)

**Comment by pandaring2you** [comment]
From Daniel: Monitoring of Validators' balance has been successfully setup
I've just spoken with the guys at Tenderly and they assured me that we now have custom balance alerts for our validator EOAs.
Whenever one of the following addresses gets below 5 ETH balance, we'll be notified.
0x0D7dEF5C00a8B6ddc58A0255f0a94cc739C6d0B5
0x9B4002670C210A3b64e13807250BE62B8dEae201
0xbF45BFc92ebD305d4C0baf8395c4299bdFCE9EA2
0xeB29C7016eDd2D6B413fceE4C51474FED058005a
I setup a forwarding filter so that if that happens, @Jordan (PST Timezone), @Jazear Brooks, @Aidan Musnitzky, @Yves Messy and I will receive the email.
Right now I'm not sure what the format of that alert will be, so I'm forwarding every email I get from Tenderly. Please let me know if you receive spam, or if you'd like to be removed from this forwarding list (or if you'd like to be added to the list)

https://sifchain.slack.com/archives/C01DZ17890D/p1632854684312700
