### ISSUE TITLE
Block OFAC list from Peggy Smart Contracts (Ethereum -> Sifchain)

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1943]
Asks:

1) For importing from Ethereum and future EVM chains we must block the transaction for the following addresses  https://www.treasury.gov/ofac/downloads/sdnlist.txt 

2) When the OFAC list is updated, we should refresh the list to ensure we're blocking new addresses. 

Note: OpenZepplin might already have a solution we can use

**Comment by daniportugalgit** [comment]
About OpenZeppelin: I didn't find a blocklist contract in their repo.

Took a look at the list. The format is something like this:
```
KARASAVIDI, Dmitrii (a.k.a. KARASAVIDI, Dmitriy), Moscow, Russia;
DOB 09 Jul 1985; Email Address 2000@911.af; alt. Email Address
dm.karasavi@yandex.ru; Gender Male; Digital Currency Address - XBT
1Q6saNmqKkyFB9mFR68Ck8F7Dp7dTopF2W; alt. Digital Currency Address -
XBT 1DDA93oZPn7wte2eR1ABwcFoxUFxkKMwCf; Digital Currency Address -
ETH 0xd882cfc20f52f2599d84b8e8d58c7fb62cfe344b; Digital Currency
Address - XMR
5be5543ff73456ab9f2d207887e2af87322c651ea1a873c5b25b7ffae456c320;
Digital Currency Address - LTC LNwgtMxcKUQ51dw7bQL1yPQjBVZh6QEqsd;
Digital Currency Address - ZEC t1g7wowvQ8gn2v8jrU1biyJ26sieNqNsBJy;
Digital Currency Address - DASH XnPFsRWTaSgiVauosEwQ6dEitGYXgwznz2;
Digital Currency Address - BTG GPwg61XoHqQPNmAucFACuQ5H9sGCDv9TpS;
Digital Currency Address - ETC
0xd882cfc20f52f2599d84b8e8d58c7fb62cfe344b; Passport 75 5276391
(Russia) expires 29 Jun 2027 (individual) [CYBER2].

KARASAVIDI, Dmitriy (a.k.a. KARASAVIDI, Dmitrii), Moscow, Russia;
DOB 09 Jul 1985; Email Address 2000@911.af; alt. Email Address
dm.karasavi@yandex.ru; Gender Male; Digital Currency Address - XBT
1Q6saNmqKkyFB9mFR68Ck8F7Dp7dTopF2W; alt. Digital Currency Address -
XBT 1DDA93oZPn7wte2eR1ABwcFoxUFxkKMwCf; Digital Currency Address -
ETH 0xd882cfc20f52f2599d84b8e8d58c7fb62cfe344b; Digital Currency
Address - XMR
5be5543ff73456ab9f2d207887e2af87322c651ea1a873c5b25b7ffae456c320;
Digital Currency Address - LTC LNwgtMxcKUQ51dw7bQL1yPQjBVZh6QEqsd;
Digital Currency Address - ZEC t1g7wowvQ8gn2v8jrU1biyJ26sieNqNsBJy;
Digital Currency Address - DASH XnPFsRWTaSgiVauosEwQ6dEitGYXgwznz2;
Digital Currency Address - BTG GPwg61XoHqQPNmAucFACuQ5H9sGCDv9TpS;
Digital Currency Address - ETC
0xd882cfc20f52f2599d84b8e8d58c7fb62cfe344b; Passport 75 5276391
(Russia) expires 29 Jun 2027 (individual) [CYBER2].
```

The file contains 188.468 lines, ~20  of which matter to us. It's not structured and it does not look professional. I wonder if there is any other source for the information we need. It would be great if we didn't have to parse this file, or if OFAC has a standard for reading data from this file - do they guarantee the format won't change? Do they guarantee everything follows the same standards in this text file? If we set up a parser and it fails to pick up an address because the format is incorrect, is that our problem? We need to discuss this.

**Comment by pandaring2you** [comment]
https://github.com/0xB10C/ofac-sanctioned-digital-currency-addresses

Use regex to find ethereum addresses. Can also use a function to check if isEthereumAddress regardless of EVM.

**Comment by jzvikart** [comment]
* Added integration test for ethereum -> sifchain transfer blocklist
* The test checks ETH and ERC20 token transfers separately
* For blocked addresses the test checks that the transaction is reverted
* For non-blocked addresses the test checks that the "LogLock" event is emitted by bridge bank and that the funds arrive to destination Sifchan account

**Comment by pandaring2you** [comment]
hey @jzvikart thanks for the update - so just so i understand, it sounds like the tests are complete and passing (correct me if im wrong). 

And based on @daniportugalgit's comment:

"One thing we might want to do together is go over the blocklist PR for Peggy 1. It does have a lot of changes, I think something like 50 files. It could be a somewhat daunting task to review that in isolation. Do we want to schedule a meeting to go over that PR together? Like Monday?"

It sounds like there will be one last review with Michael and Daniel for extra caution. so once that's done, we need to (I think Daniel had a more clear list than this, but can't find it rn):

0) Need to transfer ownership of blocklist contract to Brent
1) TEST
2) Need to run a script to deploy the bridgebank and registering the blocklist in the bridgebank
3) Populate the blocklist
4) TEST
5) Run cron job and double check.

**Comment by pandaring2you** [comment]
Dependent on #2091 . Could theoretically launch without 2091, but would incur an arduous recovery process. @pandaring2you - check with Sifnode on timing - for now, let's wait to deploy this until we get #2091 resolved.

**Comment by jzvikart** [comment]
**Work in progress** - this branch is not ready to be merged at the moment.

As discussed, I temporarily removed my changes from this branch because we want to merge integration framework first to develop and then merge develop into this branch. I will re-add my changes later on top of that, and after we receive the response from Sifnode team.

I saved the previous branch as jure/blocklist-v2-backup.

**Comment by jzvikart** [comment]
Sifnode team is currently overloaded, ask for status around 2021-11-16

**Comment by jzvikart** [comment]
Work in progress complete. Branch `blocklist-v2` has now been restored to its intended state. `test_blocklist.py` is working and passing.

**Comment by pandaring2you** [comment]
Re-opening as this still needs to be deployed as an upgrade to our smart contracts. Daniel mentioned that both him and IM need to coordinate execution. Daniel has a PR waiting on approval and will talk with IM tomorrow.

**Comment by pandaring2you** [comment]
1) Setup cron job to update blocklist 
2) Upgrade contracts w/Brent - need to check the setup for the cron job. - will check on timing once synce w/Brent

Note: Take a look at the xml sdn list.

**Comment by daniportugalgit** [comment]
About the XML file: it's definetely better than a plain text file, even if they didn't organise things in the best way possible.
As we discussed, we have to ship this asap, so we can't change the scope right now, but after we publish the current version of the script, we shall look into improving it.

**Comment by pandaring2you** [comment]
Currently in audit with Halborn: https://sifchain.slack.com/archives/C022JNCFKFA/p1641239600058100?thread_ts=1640045188.056100&cid=C022JNCFKFA

**Comment by pandaring2you** [comment]
Audit completed. Delay deployment until IM and myself return from pto (week of 1/24)

**Comment by marshsif** [comment]
@pandaring2you @intl-man can we mark this as complete?

**Comment by pandaring2you** [comment]
Remaining step is to create
