### ISSUE TITLE
(On-Going) Merge Develop Into Future/Peggy2 Every Friday

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#1951]

**Comment by pandaring2you** [comment]
There were massive refactors on develop, resulting in merge conflicts. Pausing this on an ongoing basis until we have our integration tests working and .44 upgrade.

**Comment by pandaring2you** [comment]
Restart this next week, beginning with a massive merge.

**Comment by pandaring2you** [comment]
Planning on doing this as a team after Replace Hardhat. @smartyalgo to take an initial look at how much work this will be.

**Comment by pandaring2you** [comment]
will be merging develop into future/peggy2 this friday

**Comment by pandaring2you** [comment]
ETA EOD

**Comment by pandaring2you** [comment]
Develop has been merged to peggy2

**Comment by smartyalgo** [comment]
Merged. Closing
