### ISSUE TITLE
BUG: Akash to Sif tx fails, but FE DEX shows success (NON-BLOCKING)

### ISSUE THREAD

**Issue by marshsif** [Sifchain/sifnode#1961]
How to reproduce:
Ivan was able to reproduce this error by temporarily disabling cETH imports and then attempting to perform an import of cETH.

How to resolve:
FE Team will need to make an API call to verify that a tx succeeded. Ivan spoke with Andrew about the particular API endpoint needed.

========
template:
**Current behavior**
Please describe the issue you are facing.

**Expected behavior**
Please describe what you were expecting to happen when performing your operation.

**Steps to reproduce**
Please provide an itemized list of steps we can take in order to reproduce the issue

Identify exact point in reproduction steps where expectation is violated

Example of identifying point where expectation is violated:

First do A
Then do B
Then C should occur
But D occurs instead

It is implied that fixing the issue means C will have occur after A and B.  

**What tokens are you interacting with when this issue occurs?**
Please list the "From" and "To" tokens (eg. From: cETH, To: Rowan

**Screenshots**

**Ethereum (If applicable) : Please provide relevant info**
Eg. Your Ethereum address, tx hash (EtherScan link)

**Sifchain (If applicable) : Please provide relevant info**
Eg. Your Sifchain address, link to tx on block explorer

**Additional context**

**Other Helpful Bug Filing Info**

Don't duplicate (make sure issue hasn't already been filed)

Don't mention multiple problems in one issue (just create a new issue if you observe multiple issues)

Make the issue objective, don't speculate or add opinion that isn't verifiable

Add a clear title that includes a relevant area of the code (for example: [Peggy] or [Chainops])

Format issue in markdown

Where possible, include links to relevant code on Github for easy search or copy code snippets

Where possible, include code snippets from the command line to easily search

**Comment by ajoslin** [comment]
Regarding the packet_acks endpoint to check for this failure - I mentioned that the ack endpoint gave me no differential data between a successful and unsuccessful import in the case of sifnode whitelist rejecting the tx. Tried it several times. 

I am on mobile right now but can dig up more details later

when this fails in this way, we do refund the user so it isn’t end of the world. I think it’s as good as it will get.

**Comment by marshsif** [comment]
I'm going to reopen because we may want to address this.

**Comment by ajoslin** [comment]
https://github.com/Sifchain/sifchain-ui/pull/289

**Comment by marshsif** [comment]
The problem is that FE DEX relies on packet received callback to determine success or failure. This is not sufficient. 

How To Resolve:
It needs to look for an ack packet (with appropriate, sequence number, acct number and status)
