### ISSUE TITLE
BUG: import of a non-native Akash token (such as Photon) fails. 

### ISSUE THREAD

**Issue by marshsif** [Sifchain/sifnode#1962]
How to Reproduce
Export Photon to Akash. Then try to import it back. The import tx will fail.

Possible root cause
whitelisting/registry issue import config

============
TEMPLATE

**Current behavior**
Please describe the issue you are facing.

**Expected behavior**
Please describe what you were expecting to happen when performing your operation.

**Steps to reproduce**
Please provide an itemized list of steps we can take in order to reproduce the issue

Identify exact point in reproduction steps where expectation is violated

Example of identifying point where expectation is violated:

First do A
Then do B
Then C should occur
But D occurs instead

It is implied that fixing the issue means C will have occur after A and B.  

**What tokens are you interacting with when this issue occurs?**
Please list the "From" and "To" tokens (eg. From: cETH, To: Rowan

**Screenshots**

**Ethereum (If applicable) : Please provide relevant info**
Eg. Your Ethereum address, tx hash (EtherScan link)

**Sifchain (If applicable) : Please provide relevant info**
Eg. Your Sifchain address, link to tx on block explorer

**Additional context**

**Other Helpful Bug Filing Info**

Don't duplicate (make sure issue hasn't already been filed)

Don't mention multiple problems in one issue (just create a new issue if you observe multiple issues)

Make the issue objective, don't speculate or add opinion that isn't verifiable

Add a clear title that includes a relevant area of the code (for example: [Peggy] or [Chainops])

Format issue in markdown

Where possible, include links to relevant code on Github for easy search or copy code snippets

Where possible, include code snippets from the command line to easily search

**Comment by marshsif** [comment]
Ivan, you mentioned that you would work on a unit test for this issue. This replaces a prior ticket #1956.

**Comment by iverc** [comment]
@jon-sif Verified that the described flow works as expected.

**Comment by iverc** [comment]
@marshsif PR with multichain transfer test:
https://github.com/Sifchain/sifnode/pull/1968

**Comment by sheokapr** [comment]
Tested PHOTON export/import to Akash successfully.
