### ISSUE TITLE
BUG: conflicting token settings cause issues with imports

### ISSUE THREAD

**Issue by marshsif** [Sifchain/sifnode#1966]
Issue:
cETH had incorrect registry config that conflicted with xETH and cause problems with imports.

Requirements:
cETH on Sifchain needs to be exported to IBC as xETH and only xETH. Sifchain should only support importing of xETH via IBC to cETH on Sifchain.

Root Cause:
The permissions for several tokens need to be corrected to address this issue.

============
TEMPLATE

**Current behavior**
Please describe the issue you are facing.

**Expected behavior**
Please describe what you were expecting to happen when performing your operation.

**Steps to reproduce**
Please provide an itemized list of steps we can take in order to reproduce the issue

Identify exact point in reproduction steps where expectation is violated

Example of identifying point where expectation is violated:

First do A
Then do B
Then C should occur
But D occurs instead

It is implied that fixing the issue means C will have occur after A and B.  

**What tokens are you interacting with when this issue occurs?**
Please list the "From" and "To" tokens (eg. From: cETH, To: Rowan

**Screenshots**

**Ethereum (If applicable) : Please provide relevant info**
Eg. Your Ethereum address, tx hash (EtherScan link)

**Sifchain (If applicable) : Please provide relevant info**
Eg. Your Sifchain address, link to tx on block explorer

**Additional context**

**Other Helpful Bug Filing Info**

Don't duplicate (make sure issue hasn't already been filed)

Don't mention multiple problems in one issue (just create a new issue if you observe multiple issues)

Make the issue objective, don't speculate or add opinion that isn't verifiable

Add a clear title that includes a relevant area of the code (for example: [Peggy] or [Chainops])

Format issue in markdown

Where possible, include links to relevant code on Github for easy search or copy code snippets

Where possible, include code snippets from the command line to easily search

**Comment by iverc** [comment]
https://github.com/Sifchain/sifnode/pull/1986
