### ISSUE TITLE
[Token Registry] Add JUNO chain on sifchain network

### ISSUE THREAD

**Issue by nikohosn** [Sifchain/sifnode#1979]
Add Juno to Sifchain

**Comment by gzukel** [comment]
Juno-1 nodes deployed to testnet and betanet, ts-relayer has been deployed to testnet for juno-1 network on public rpc endpoints for now.

**Comment by timlind** [comment]
@nikohosn can this be closed?

**Comment by bksifchain** [comment]
@nikohosn can we close this?
