### ISSUE TITLE
Fix Peggy2 smart contracts wrt upgrades

### ISSUE THREAD

**Issue by daniportugalgit** [Sifchain/sifnode#2025]
- [x] Add the blocklist to the contract suite
- [x] Add/update blocklist isolated unit tests
- [x] Update the blocklist as per the last changes on Peggy 1.0
- [x] Add Blocklist + BridgeBank + CosmosBridge unit tests
- [x] Review unused variables: are there any vars that are already deprecated and didn't make it to production?
- [x] Test upgrades with a mainnet fork and make sure they are safe and working.
- [x] Test Coverage: reach 100% coverage for all non-mock contracts (reached 100% in CosmosBrdige and 99.36% in BridgeBank, which is enough)
- [x] Re-enable the contract-sizer
- [x] Remove everything about the Ethereum Whitelist (as it's deprecated in Peggy2)
- [x] Add tests with Rowan (they were bundled together with EthWhitelist, that has been removed)
- [x] Bring Hardhat initialization goodies to this branch (logs, forking, colors)
- [x] Refactor BridgeBank (storage overlap)
- [x] Refactor CosmosBridge (storage overlap)

TEST COVERAGE:
- [x] Re-enable test coverage with new tool that works with Peggy 2.0 codebase
- [x] Add a command to run the test coverage
- [x] Adjust the command to run tests
- [x] CosmosBridge: `onlyValidator()`
- [x] CosmosBridge: `changeOperator()`
- [x] BridgeBank: `getDenom()` when we already know the token's denom
- [x] BridgeBank: `getDenom()` when the contract does not have a `cosmosDenom` property
- [x] BridgeBank: `_burnTokens()` when `tokenAddress` is the old eRowan token (can't do this in a normal test, as we would need to deploy the erowan contract to the exact same address it has in production).
- [x] EthereumWhitelist: `onlyEthTokenWhiteList()` (remove it as it's deprecated)

BUGS:
- [x] Fix bug in which the BridgeBank deploys new tokens but doesn't mint
- [x] Add unit tests to guarantee that whenever BridgeBank deploys a new token, it also gets minted correctly

FINAL SCRIPT:
- [x] Create and test the final script that will do all steps of the upgrade from Peggy 1 to Peggy 2

Here's the draft PR I'm working on: https://github.com/Sifchain/sifnode/pull/2078

**Comment by pandaring2you** [comment]
Will need to refactor bridgebank and cosmos bridge due to overlap in the storage layout. 

-  Refactor BridgeBank (storage overlap)
- Refactor CosmosBridge (storage overlap)

**Comment by pandaring2you** [comment]
Assuming no interrupts, should be able to complete this sprint

**Comment by daniportugalgit** [comment]
Finished the work per se. Now we have to resolve merge conflicts.

**Comment by pandaring2you** [comment]
@daniportugalgit to setup meeting to review all changes including blocklist and upgrade scripts from peggy 1.0 to 2.0.
