### ISSUE TITLE
Assess how to improve CLP code coverage and implement unit tests

### ISSUE THREAD

**Issue by timlind** [Sifchain/sifnode#2045]
Motivation: The current SDK upgrade involves fixing tests within the integration test environment, which would be much more efficient to maintain if they existed in the GoLang codebase, which can be achieved by improving code coverage.

**Comment by wilsonc2020** [comment]
So now we increased code coverage for folder `x/clp` from 44.13% based on `develop` branch to `72.65%` see my test branch `code_cover_clp_keeper_draft`.

Here is codecov reports for these two branch and if you compare you can see the improvement : 

`code_cover_clp_keeper_draft` : https://app.codecov.io/gh/Sifchain/sifnode/branch/code_cover_clp_keeper_draft

`develop`: https://app.codecov.io/gh/Sifchain/sifnode/branch/develop

I have another branch `code_cover_clp_types` to track my work to improve codecov for folder `x/clp/types` once I am done and we merge that into develop, the codecov for clp should approach 80%.

**Comment by wilsonc2020** [comment]
codecov improve for keeper folder is under review: https://github.com/Sifchain/sifnode/pull/2244
codecov improve for types folder is WIP: https://github.com/Sifchain/sifnode/commits/code_cover_clp_types

**Comment by pandaring2you** [comment]
ETA have Tim's comments. Merge ETA tomorrow

**Comment by marshsif** [comment]
This is ready for review. @timlind and @khdegraaf to review

**Comment by wilsonc2020** [comment]
Merged. https://github.com/Sifchain/sifnode/pull/2276
