### ISSUE TITLE
[Peggy] Relayer crash if not enough locked assets

### ISSUE THREAD

**Issue by juniuszhou** [Sifchain/sifnode#206]
Relayer crash during the test. the error message as following.
2020/11/04 09:13:18 VM Exception while processing transaction: revert Not enough locked assets to complete the proposed prophecy

**Comment by utx0** [comment]
Hey @juniuszhou can you give us some more details around how to reproduce this issue? Thanks

**Comment by juniuszhou** [comment]
@utx0 Actually the message "2020/11/04 09:13:18 VM Exception while processing transaction: revert Not enough locked assets to complete the proposed prophecy" from your e2e testing in testnet. I created the issue to record. I think the issue could be occured if we burn much more ethereum assets than we locked in smart contract. But in realistic environment, it should never happen. And I already improved the error handling, the relayer just return an error, not crash anymore.
I think we can close the issue.

**Comment by utx0** [comment]
Yeah ok cool. ill close it off then for now. Thanks
