### ISSUE TITLE
Support Exporting of IBC tokens to Ethereum and Polygon (october-21)

### ISSUE THREAD

**Issue by zikarium** [Sifchain/sifnode#2085]
This time we're deploying the LikeCoin IBC token.

Its ERC20 version has been deployed to the Ethereum mainnet: 0x7588fEFd8D087A7EE3F568087190209F7B449b28

A new file has been created and committed to the `future/peggy2-deploy-ibc-tokens` branch: **deployed_ibc_tokens_21_Oct_2021.json**

@intl-man please run the RegisterIbcTokens script, and then handover to @pandaring2you 

Your .env variable REGISTER_TOKENS_SOURCE_FILENAME has to have the following value:
```REGISTER_TOKENS_SOURCE_FILENAME=./data/deployed_ibc_tokens_21_Oct_2021.json```

---

@pandaring2you I also sent the token to the Polygon bridge and will report back as soon as it's bridged.

**Comment by pandaring2you** [comment]
https://www.notion.so/sifchain/LikeCoin-New-Token-Runbook-0589662a6f904b33a9dc4b5ba2ada754 

@nikohosn - After Daniel receives word back from Polygon that the tokens have been bridged, we should be all good on the ethereum / polygon side. what is the timing on when sifnode wants to ibc connect to likecoin?
