### ISSUE TITLE
Block OFAC list from Sifnode (Sifchain -> Ethereum)

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#2091]
Asks:

1) For exporting from Sifchain to Ethereum and future EVM chains we must block the transaction for the following addresses https://www.treasury.gov/ofac/downloads/sdnlist.txt

2) When the OFAC list is updated, we should refresh the list to ensure we're blocking new addresses.

Related issue: #1943 (Ethereum -> Sifchain)

**Comment by pandaring2you** [comment]
hey guys - wanted to check on progress here, we still on track for Thursday to get this out?

**Comment by AustinoBombino** [comment]
hey @pandaring2you I've been asked to pull away from this issue to focus exclusively on Margin work. The rest of the team is already slated with other tasks and we're a bit shorthanded without Tim this week, so it's looking like this will need to be pushed back to next week.

If you feel this needs to take priority I would discuss with either Brian Woods or Jon Hancock to get it bumped in front of other work.

**Comment by pandaring2you** [comment]
@jon-sif - Can we schedule this work to be started on Monday? Ingrid was thinking this would be done today - we put in a superficial UI fix to bandaid this, but I think we should have a real solution for regulatory concerns soon.

**Comment by jon-sif** [comment]
@brianosaurus can you please update on who has this issue?  It's showing assigned to Tim.  Jordan needs it worked on this week.

**Comment by AustinoBombino** [comment]
@jon-sif Brian let us know yesterday morning that he needed to take the day off. I haven't seen him online yet today so not sure if he's back or not. Tim seems to still be out and Ivan is also out this week. So Sifnode as of now seems to just be me and Tanmay, and we're both occupied.

**Comment by iverc** [comment]
I think it’d make sense for Austin to keep focusing margin, while Brian and Tanmay might wanna prioritize this task over the other ingoing tasks to make it work this week.
 I might be able to look into it tomorrow or at least assist  with it.

**Comment by pandaring2you** [comment]
From Tim: "Hey Jordan, I’ve started dev on this today so will see how we can fit it in with testing and releases amongst other priorities as Marshall mentioned. "

**Comment by pandaring2you** [comment]
@timlind  - ping on this - do you have a status?

Would be great to know: 
1 - what the solution will look like
2 - testing/release priorities and estimated timeline

**Comment by pandaring2you** [comment]
Tim: This is dev complete and waiting to merge in to develop, aside for the script to keep the list updated, which is being borrowed from the Peggy work. Do you know if that’s merged in yet?

Jordan (PST Timezone):spiral_calendar_pad:  3 days ago
Awesome! Not sure, I believe it should be cc @Daniel Portugal

Tim Lind  10 hours ago
@Daniel Portugal When do you plan on merging the peggy scripts for the OFAC list?

Daniel Portugal  7 hours ago
@Tim Lind I expect it to be merged either today or tomorrow. Jure is finalizing the integration tests, we're almost there

Daniel Portugal  5 hours ago
@Tim Lind It's merged into develop

**Comment by pandaring2you** [comment]
from Tim https://sifchain.slack.com/archives/C01ERUNS2Q0/p1637680844203400

**Comment by pandaring2you** [comment]
This is currently on betanet
