### ISSUE TITLE
Integration Testing Peggy 2.0 Framework

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#2097]
@pandaring2you commented on [Tue Oct 26 2021](https://github.com/Sifchain/sifchain-chainops/issues/107)

Placeholder to be filled in after jure and the team decide on the testing framework at 10/27 meeting

**Comment by jzvikart** [comment]
@pandaring2you If I remember correctly, this ticket was a placeholder about phasing out devenv in favor of integration framework? If so, this ticket can be closed as the steps are already contained in other tickets (i.e. #2110, #2129, #2211).
