### ISSUE TITLE
Investigate peggy1 ebrelayer failure incident

### ISSUE THREAD

**Issue by smartyalgo** [Sifchain/sifnode#2111]
On Oct 27 ~10am CST - 2:30pm, 2 of the 4 ebrelayer was not running in production. This caused an out-of-market incident, and affected txs.

Deliverable:
- Investigate why it happened
- Measures to prevent future occurrences.

**Comment by pandaring2you** [comment]
hey @intl-man - is this on your team's radar for this sprint?

**Comment by pandaring2you** [comment]
resolved. @smartyalgo please add PR that resolved this for future reference

**Comment by smartyalgo** [comment]
PR: https://github.com/Sifchain/sifnode/pull/2107
