### ISSUE TITLE
Fix claim already exists error in watcher test

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2121]

**Comment by Brando753** [comment]
Issue was occurring because test was logging claims at the LogToEvent function call which is called not only when a claim arrives but also when the relayer wakes up and checks the last event which updated the nonce.

Line 236-239 ethereum.go:
```go
	event, isBurnLock, err := sub.logToEvent(oracletypes.NetworkDescriptor(networkID.Uint64()),
		bridgeBankAddress,
		bridgeBankContractABI,
		ethLogs[0])

```

Line 286-291 ethereum.go
```go
		for _, ethLog := range ethLogs {
			event, isBurnLock, err := sub.logToEvent(oracletypes.NetworkDescriptor(networkID.Uint64()),
				bridgeBankAddress,
				bridgeBankContractABI,
				ethLog)

```

LogToEvent in ethereum.go outputs the log watcher.ts watches as a claim on line 413:
```go
	sub.SugaredLogger.Debugw(internal.PeggyTestMarker, "kind", "EthereumEvent", zap.Reflect("event", event), "txhash", cLog.TxHash.Hex())
```

Resolution, since we are watching for claims place a log in the handleEthereumEvent method on line 444 like so:
```go
			if prophecyClaim.EthereumLockBurnNonce == nextLockBurnNonce {
				prophecyClaims = append(prophecyClaims, &prophecyClaim)
				sub.SugaredLogger.Debugw(internal.PeggyTestMarker, "kind", "EthereumProphecyClaim", zap.Reflect("event", event))
				nextLockBurnNonce++
			} else {
```
Then change the file src/watcher/ebrelayer.ts toEvmRelayerEvent to look for "EtheumProphecyClaim instead of EthereumEvent:

```ts
export function toEvmRelayerEvent(x: any): EbRelayerEvent | undefined {
  if (x["M"] === "peggytest") {
    switch (x["kind"]) {
      case "EthereumProphecyClaim":
        return { kind: "EbRelayerEvmEvent", data: x }
        break
```

@banshee Please review these changes and let me know if this makes sense and is an acceptable solution to the problem.

**Comment by banshee** [comment]
Works now.
