### ISSUE TITLE
Output useful tools from Integration ENV

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2129]
IntegrationENV should output a file with useful commands already filled out for operating sifnode correctly to increase development velocity.

**Comment by smartyalgo** [comment]
Love this. Maybe even source it and it gives us alias so we dont hv to type out the whole thing.

**Comment by pandaring2you** [comment]
No longer doing on devenv. Moving to integration env.

**Comment by banshee** [comment]
You can look at test/integration/environment_setup.sh for an example of how we used to do this for the old environment.

**Comment by pandaring2you** [comment]
Finished!
