### ISSUE TITLE
Remove Decimals, Name, and Symbol from DenomHash generation

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2135]
The current GetDenomHash implementation uses the contract address, network descriptor, name, decimals, and symbol to generate the denom hash on sifnode. This should only use the contract address, and network descriptor to avoid problems with ERC20 tokens that could change those fields from being seperated in our keepers.

**Comment by pandaring2you** [comment]
to ensure the hash is only based on network id and address to avoid the same token have different hashes
