### ISSUE TITLE
Add seperators '/' to hashed strings that have seperate values

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2168]
When we hash strings such as in the prophecy ID and denom hash we should separate the values in the string being hashed by a '/'. This is best practice in any hashes to prevent the ability to construct colliding hashes with different inputs to variables. i.e. if var A is "123" and B is "456" without the separator an attacker could pass in the variables var A "1" B "23456" which would hash the exact same without a separator.

**Comment by pandaring2you** [comment]
@Brando753 to check if this is actually done
