### ISSUE TITLE
Document the current Peggy 2.0 Lock/Burn Arch

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2180]
We need a document to act as a source of truth for how Peggy 2.0 should be handling locks/burns on both sifnode and evm side for evm native assets, cosmos native assets, and double pegged assets.

**Comment by Brando753** [comment]
https://docs.google.com/document/d/1KhaQBDonE6H3qQ0Q_NdWYRF86xNacKKavz_2BkA7iv0/edit?usp=sharing

Current document in progress

**Comment by Brando753** [comment]
Need to document the way double pegged locks determine if a bridge token has already been deployed. Need to add some visual diagrams of the flow.

**Comment by Brando753** [comment]
RFC is open to peggy team for review. Diagrams may still get readability tweaks.

**Comment by pandaring2you** [comment]
Dot files converted to sequence diagrams. Moving docs to doxify tool
