### ISSUE TITLE
[ChainOps] monkey-bars-testnet-3/genesis.json - Duplicate Validator Monikers

### ISSUE THREAD

**Issue by 59023g** [Sifchain/sifnode#219]
https://raw.githubusercontent.com/Sifchain/networks/feature/genesis/testnet/monkey-bars-testnet-3/genesis.json

For all 4 validators in Genesis the monikor is `misty-voice`. They should be different.

<img width="1214" alt="Screen Shot 2020-11-06 at 8 13 39 PM" src="https://user-images.githubusercontent.com/5235538/98429499-95fee980-206c-11eb-8560-593a1a76490e.png">

**Comment by utx0** [comment]
Marking this as a P3 for now. As its now really a blocker for our next major goal.

**Comment by jkbrooks** [comment]
@59023g is this still an issue? If so, please file with the standard format from the dev charter. #308 has an example. We can then get it up on Gitcoin

**Comment by 59023g** [comment]
I don't see this issue in latest genesis: https://github.com/Sifchain/networks/blob/feature/genesis/testnet/latest.json. 
Closing now
