### ISSUE TITLE
Debug set-registry

### ISSUE THREAD

**Issue by brianosaurus** [Sifchain/sifnode#2210]
Set registry's cli command might have a bug where it cannot accept a JSON file with multiple registry entries. Debug and test this to ensure or fix so that it works properly.

Also, look into cli testing so these kinds of bugs don't slip through in the future.

**Comment by brianosaurus** [comment]
See also: https://app.zenhub.com/workspaces/current-sprint---engineering-615a2e9fe2abd5001befc7f9/issues/sifchain/sifnode/1992

**Comment by marshsif** [comment]
Hey @brianosaurus what is the status of this? Is it required for .43? If not, remove it from the release.

**Comment by brianosaurus** [comment]
Peggy said they would handle removing this feature. Closing
