### ISSUE TITLE
Improve unit testing in dispensation module 

### ISSUE THREAD

**Issue by khdegraaf** [Sifchain/sifnode#2232]
Background task when you are blocked, we need to improve our code coverage overall, but you should focus on this.

**Comment by sheokapr** [comment]
After PR merge, coverage seems to have bumped up from 44% to 94% for dispensation/types.
**Coverage Before:**

![image](https://user-images.githubusercontent.com/22618719/148431947-9d7b0c66-1742-4846-be8e-ddb83a279334.png)

**Coverage After:**
![image](https://user-images.githubusercontent.com/22618719/148432134-7686b69c-0961-4374-8910-2353f01ae2f7.png)

**Comment by pandaring2you** [comment]
Some lint errors to clean up and @khdegraaf to codecov numbers before merge

**Comment by pandaring2you** [comment]
@sheokapr to create a PR for kevin to review eta tomorrow

**Comment by sheokapr** [comment]
Added/Updated unit tests for files in dispensation/keeper directory. I have committed changes as part of the original PR- https://github.com/Sifchain/sifnode/pull/2324

**Comment by pandaring2you** [comment]
@khdegraaf to confirm after @sheokapr fixes merge conflicts.

**Comment by sheokapr** [comment]
@khdegraaf - thanks for sorting out the merge conflicts and merging the changes to develop, can we close this ticket now?

**Comment by pandaring2you** [comment]
Has been merged
