### ISSUE TITLE
Daniel Transition Plan 

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#2253]
Hey Daniel - creating a task to track your transition over the next 10 days. Can you add to this list? I'm trying to think of everything we will need from you before you leave. Thanks!

https://docs.google.com/spreadsheets/d/1mQ7uzlb6r6nUyWd2BewBFnUmqtsfmDFnhhqb5mZxlmk/edit#gid=0

**Comment by daniportugalgit** [comment]
Hey Jordan, thanks!

For sure, I'll add to that list.
