### ISSUE TITLE
Change how Peggy 2.0 handles Denoms

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2277]
We are moving away from using a SHA256 hashed denoms to use more human readable syntax. Convert the DenomHash to the new format:

```
sifbridge<version number three digits><network id>0x<token contract address>
```
Using the null address for native token assets.

**Comment by jzvikart** [comment]
When you change the algorithm let me know so that I can update it also in siftool.

**Comment by smartyalgo** [comment]
Here are some concerns for changing the denom
- Do we need to perform migration for what's currently in the banking module
- How do we handle IBC imports with old denom, do we need to burn and mint new denom for the user?
- The rewards team uses token registry for looking up asset, we'll need to perform migration on that too

**Comment by Brando753** [comment]
Work started on this ticket

**Comment by pandaring2you** [comment]
ETA tonight

**Comment by Brando753** [comment]
#2510 Was merged finishing this out.
