### ISSUE TITLE
[Peggy] ebrelayer doesnt restart websocket connection if dropped

### ISSUE THREAD

**Issue by utx0** [Sifchain/sifnode#228]
In debugging the ebrelayer, I noticed that the websocket connect to infura dropped and the connection wasnt restarted. From this point onwards no more txs were witnessed 

```
E[2020-11-09|04:11:15.875] websocket: close 1006 (abnormal closure): unexpected EOF 
```

**Comment by jkbrooks** [comment]
@utx0 @ilyabukalov is this still an issue? If so, please file with the standard format from the dev charter. #308 has an example. We can then get it up on Gitcoin

**Comment by ilyabukalov** [comment]
fixed and merged here: https://github.com/Sifchain/sifnode/pull/291
@utx0 please confirm if we have anything else?

**Comment by utx0** [comment]
Yep this all looks like its working/fixed.
