### ISSUE TITLE
Minor patch for argument mismatch in ibc-go/v2@v2.0.0

### ISSUE THREAD

**Issue by brianosaurus** [Sifchain/sifnode#2293]
Submit patch to Cosmos for review. The fix is simply to change the required arguments from 3 to 2 (the correct number)

**Comment by brianosaurus** [comment]
Update: v2.0.2 has the patch on it. Testing that version.

**Comment by marshsif** [comment]
2.0.2 has a dependency on the .44 CosmosSDK. We'll have to wait until we upgrade to .44
