### ISSUE TITLE
Investigate ImmuneFi report submission: lockedFunds is always 0

### ISSUE THREAD

**Issue by jzvikart** [Sifchain/sifnode#2306]
We have a new ImmuneFi report submission (through @pgoos):

lockedFunds is always 0
Smart Contract Bug Description
EthereumBankStorage contains a mapping called lockedFunds that should indicate the amount locked of a certain token:

```
    /**
    * @notice how much funds we have stored of a certain token
    */
    mapping(address => uint256) public lockedFunds;
```
However, this mapping is never set nor updated, so it returns 0 for any inputs. I think function lockFunds was intended to update this amount but it overrides lockedTokenList instead:

```
  // Increment locked funds by the amount of tokens to be locked
  lockedTokenList[_symbol] = _token;
```
Impact
I think this value is never used internally, only for the external read, so I have assigned a severity of low.

Recommendation
function lockFunds should update lockedFunds:
```
  lockedFunds[_token] += _amount
```

**Comment by jzvikart** [comment]
According to preliminary analysis by @jzvikart and @banshee the `lockedFunds` mapping is obsolete. It was left out to save gas since all the neccessary information can be obtained in other ways. The field itself was left in place as a placeholder to preserve storage layout for backward compatibility of BridgeBank upgrades. This has no implications on security, and the proposed fix is simply to rename the field and add a comment indicating that it's deprecated. As an additional step and a best practice (suggested by @khdegraaf) we migh want to do the same for all similar cases.

**Comment by khdegraaf** [comment]
I commented at ImmuneFi with a slightly edited version of this, and asked the Hacker to see if they disagreed at all with this.

**Comment by jzvikart** [comment]
From @Brando753:

> I concur this is a field that was unnecessary to track in the smart contract. It was removed by Elliot 7 months ago and the storage slot was just not commented deprecated. I cant think of any reason that field would need to be tracked on the smart contract side. The system as a whole should prevent unlocking funds that are not locked in.
