### ISSUE TITLE
Create package for datapipeline team to generate cosmos events per peggy2 operation

### ISSUE THREAD

**Issue by smartyalgo** [Sifchain/sifnode#2332]
Data pipeline team needs a list of events for each peggy2 operation.
Deliverable:
- Package to start devenv. (devenv /w instructions)
- Simple command line tool/instructions to invoke each peggy2 operation. 

Point of contact: Dae

**Comment by pandaring2you** [comment]
@smartyalgo to sync with @jzvikart to see if we can reuse this work for UI's peggy2 environment

**Comment by pandaring2you** [comment]
to start this sprint

**Comment by pandaring2you** [comment]
Michael to sync with Dae to handover by 2/23

**Comment by pandaring2you** [comment]
from @daechoi :

"Is there a documented event signature and api endpoint that we can interrogate to extract the data?"

@smartyalgo - can you follow up with Dae to make sure he's fully set up? Thanks!

**Comment by pandaring2you** [comment]
Michael to chat w/Dae tomorrow. Might need to document events

**Comment by smartyalgo** [comment]
This ticket can be closed, this isnt Datapipeline's concern for now. Relevant tasks are https://app.zenhub.com/workspaces/current-sprint---engineering-615a2e9fe2abd5001befc7f9/issues/sifchain/sifnode/2497
