### ISSUE TITLE
[Testing] Peg in a bunch of assets into TestNet

### ISSUE THREAD

**Issue by intl-man** [Sifchain/sifnode#2334]
We recently had to re-build TestNet. As such, we need to re-run the scripts to peg in a bunch of assets, like we did last time (as all balances have been reset).

**Comment by pandaring2you** [comment]
Working with @jzvikart . Expected to finish minting of tokens by EOD

**Comment by sheokapr** [comment]
Minting was done last week, so this ticket can be closed now.
