### ISSUE TITLE
Investigate Troll Token Bridgebank Interaction from integration test

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2340]
@jzvikart  reports that BridgeBank successfully locked and transmitted lock events for a troll token that transfers should loop out on.

**Comment by pandaring2you** [comment]
@jzvikart

**Comment by jzvikart** [comment]
I was referring to `test/integration/src/peggy2/test_eth_transfers.py:test_trolltoken_to_sifnode_and_back`. From what I can remember from when I was running this test myself, test was successful in passing the TrollToken from Ethereum to Sifchain, but it failed on the way back. @Brando753 said that this is not how it should be and that it should be investigated.

**Comment by pandaring2you** [comment]
@Brando753 to take a look
