### ISSUE TITLE
Halborn Audit 1

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#2342]
https://halborn.nifty.pm/public/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9qZWN0X2lkIjoienQwNHNDR2N4RHN4RiIsInNoYXJlX3Rva2VuIjp0cnVlLCJ0ZWFtX2lkIjoidVloejh6MU96RlA4RVQiLCJ0ZWFtX3VybCI6ImhhbGJvcm4iLCJ0ZWFtX3BsYW4iOiJYX0Jhc2ljX1BsYW4iLCJtZW1iZXJfaWQiOiJNMCFPckNQQjFhMVhjbSIsInJvbGVfaWQiOiJNaHp3Nm1sa2hiMGtnQyIsInJvbGVfbmFtZSI6Im1hbmFnZXIiLCJpYXQiOjE2MjI1NjI0MzEsImV4cCI6MzE5OTM2MjQzMX0.oXhZ4V7R4dl5IzJY260yipky0ILVckJ46iu0-K_G_Bs/milestones/zt04sCGcxDsxF?pub

**Comment by banshee** [comment]
We have other tickets that track this with better granularity.
