### ISSUE TITLE
Sifgen genesis needs default values from margin module

### ISSUE THREAD

**Issue by timlind** [Sifchain/sifnode#2375]
When adding a new module and using sifgen to spin up a temp net, the default genesis values for the new module are not included in the genesis.

PR https://github.com/Sifchain/sifnode/pull/2374

Attempted fix https://github.com/Sifchain/sifnode/pull/2374/commits/0465b15da192afffc5c171fcda6ffe1ae37afa91

Error
```
 sifgen network create localnet 1 /home/runner/work/sifnode/sifnode/deploy/networks 192.168.1.2 /home/runner/work/sifnode/sifnode/deploy/networks/network-definition.yml --keyring-backend test --mint-amount 999999000000000000000000000rowan,1370000000000000000ibc/FEEDFACEFEEDFACEFEEDFACEFEEDFACEFEEDFACEFEEDFACEFEEDFACEFEEDFACE

2022/01/19 15:14:17 json: cannot unmarshal string into Go struct field Params.app_state.margin.params.epoch_length of type int64

```

**Comment by marshsif** [comment]
Just want to note that this is impacting our margin timeline a little. If you can give this some attention, I'd appreciate it!

**Comment by timlind** [comment]
This has been fixed by redefining the margin genesis in sifgen and working around som serialisation quirks
