### ISSUE TITLE
Unable to start local env after merging develop

### ISSUE THREAD

**Issue by smartyalgo** [Sifchain/sifnode#2389]

**Comment by juniuszhou** [comment]
I just fixed the json output, instead will use the text format and implemented a method to parse it. 
We also need add the "--node tcp://0.0.0.0:26657" to run sifnoded command.
still issue to start witness and relayer, the contract used when start them is not corrrect.

**Comment by smartyalgo** [comment]
Using `sifnoded keys list --keyring-backend test` I notice the key it is using isnt in the keyring

**Comment by smartyalgo** [comment]
Able to start local env successfully, closing
