### ISSUE TITLE
Set export permissions on ERC-20 tokens on testnet

### ISSUE THREAD

**Issue by brianosaurus** [Sifchain/sifnode#2390]
Update ERC-20 tokens on testnet to have export permission.

**Comment by brianosaurus** [comment]
duplicate of https://github.com/Sifchain/issues/issues/1095

**Comment by sheokapr** [comment]
hey @brianosaurus - can you please set export permissions for all ERC-20 tokens, to start with you can add them for - LINK, BAT, USDT, ETH, WBTC, ZRX
Thanks
