### ISSUE TITLE
dispensation cannot accept multiple tokens

### ISSUE THREAD

**Issue by brianosaurus** [Sifchain/sifnode#2398]
From: https://sifchain.slack.com/archives/C02R4KV4KBR/p1643130936205300?thread_ts=1643119718.201700&cid=C02R4KV4KBR

If output.json contains only a single denom (we tried rowan, cusdt, and ibc hash for nyan), then it runs without issues and the output is
```
code: 0
codespace: ""
data: ""
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: '[]'
timestamp: ""
tx: null
txhash: 1B0AF3D4063D3B0F241D5AD6F6689CBB69DCDA54CDD4EF4C9C141FB8403BC05F
```
but when output.json contains multiple tokens - content like this
```json
{
  "Output": [
    {
      "address": "sif14frequ7sweaqra6u4pp8rkjgtc5hqxxcll6ppj",
      "coins": [
        {
          "denom": "rowan",
          "amount": "100"
        },
        {
          "denom": "cusdt",
          "amount": "100"
        }
      ]
    }
  ]
}
```

**Comment by marshsif** [comment]
just to note that this does not seem to be required for .43 release. If the file's denoms are in alphabetical order, it won't throw an error. Prefer to punt this until after .43 if possible.
