### ISSUE TITLE
Add test cases to smart contracts for transfers that have commissions

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2417]
As some tokens have commissions it's important that the updated bridgebank can work under those conditions and new tests need to be added for them.

e.g. BabyDoge - charges 5% for every p2p transfer and redistributes to all BabyDoge holders

**Comment by pandaring2you** [comment]
e.g. BabyDoge - charges 5% for every p2p transfer and redistributes to all BabyDoge holders

**Comment by pandaring2you** [comment]
@banshee @smartyalgo to review https://github.com/Sifchain/sifnode/pull/2441
