### ISSUE TITLE
Port improved TokenRegistry implementation back to future/peggy2

### ISSUE THREAD

**Issue by smartyalgo** [Sifchain/sifnode#2419]
We made improvements in tokenregistry module, that was removed in the develop merge. 

Deliverable:
Replace existing impl with improved impl 
Potentially merge this into develop independently to avoid future merge conflicts

**Comment by pandaring2you** [comment]
will do this after group 1 integration tests

**Comment by pandaring2you** [comment]
Duplicate of Junius's task
