### ISSUE TITLE
README Docs step: Create-Validator command raising error

### ISSUE THREAD

**Issue by HelloKashif** [Sifchain/sifnode#243]
This is based on the README instructions to create a validator. Is fails with the following error

```
moniker = "sparkling-fog"
root@sifchain-vm:~/sifnode# sifnodecli tx staking create-validator \
>     --commission-max-change-rate 0.1 \
>     --commission-max-rate 0.1 \
>     --commission-rate 0.1 \
>     --amount 5000000rowan \
>     --pubkey $(sifnoded tendermint show-validator) \
>     --moniker sparkling-fog \
>     --chain-id monkey-bars \
>     --min-self-delegation 1 \
>     --gas auto \
>     --from sparkling-fog \
>     --keyring-backend file
failed to get from fields: The specified item could not be found in the keyring
```

however replacing with --arg=value format with these works. Either we should update the README with --arg=value syntax or find out why this doesn't work

**Comment by c29r3** [comment]
sifnodecli tx staking create-validator \
    --amount=1000000rowan \
    --pubkey=$(sifnoded tendermint show-validator) \
    --moniker=sparkling-fog \
    --chain-id=monkey-bars \
    --commission-rate="0.10" \
    --commission-max-rate="0.20" \
    --commission-max-change-rate="0.01" \
    --min-self-delegation="1" \
    --gas="auto" \
    --gas-adjustment="1.2" \
    --gas-prices="0.025rowan" \
    --from=sif168zek9ug572meeg4w6epkhv4e9cdccuumy66gq \
    --yes
