### ISSUE TITLE
Investigate need for prophecy id in peggy 2.0

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#2434]
2 places where we maintain a function to turn a transaction into a prophecy id. we might not need this in the smart contract (saving gas and less code complexity). might be a vestigial limb from peggy 1.0. Not needed for peggy 2.0 MVP, can delay till after peggy 2.1.

**Comment by Brando753** [comment]
Upon review, the prophecy ID is very much required as it's the only data being signed by the witnesses to verify prophecy claims. Recommend verifying that all data is the prophecy claim is hashed in the prophecy id.

**Comment by pandaring2you** [comment]
High priority for auditing timelines

**Comment by pandaring2you** [comment]
Est. EOD
