### ISSUE TITLE
Re-implement register all as single transaction

### ISSUE THREAD

**Issue by juniuszhou** [Sifchain/sifnode#2460]
The previous implementation of the register all includes a loop and generates one transaction for each item in JSON file. we need to change it, use one transaction to add all items.

**Comment by pandaring2you** [comment]
@Brando753 to review today

**Comment by pandaring2you** [comment]
Correction: @Brando753 to review tomorrow

**Comment by pandaring2you** [comment]
got comments, working on changes

**Comment by pandaring2you** [comment]
ETA today

**Comment by pandaring2you** [comment]
Brando to make changes ETA EOD

**Comment by juniuszhou** [comment]
close as pr merged.
