### ISSUE TITLE
Demo: minting test tokens for Tempnet

### ISSUE THREAD

**Issue by jzvikart** [Sifchain/sifnode#2470]
From @khdegraaf (from Marshall)

> Kevin and testing team to present on integration testing, manual testing of testnet, token minting, account setup on LocalNet & TestNet
> 
> Testing team's goal in next week is to have a TempNet that runs integration tests (sifnode & sifchain.js), mints tokens, funds accounts
> 
> Ensure that Sifnode can run testnet envs, run integration tests, easily mint tokens and fund accounts for dev and testing.

The goal is to integrate siftool's token minting into Tempnet via "customization plugins" as discussed with Lance. We want to make a 5-10 min demo for Sifnode team how to do it.

Working branch: https://github.com/Sifchain/sifchain-devops/tree/jure/mint-test-tokens

**Comment by jzvikart** [comment]
Current blockers:
- Tempnet on AWS: transactions are not being relayed across the bridge from Ethereum to Sifnode
- Tempnet on Minikube: cannot connect to ganache, random pods crashes

**Comment by pandaring2you** [comment]
Tempnet on minikube blocker - should be able to debug w/o Lance since he's away
eRowan not whitelisted on Tempnet inconsistency - might be related to transactions not being relayed across the bridge issue.

**Comment by jzvikart** [comment]
Fixed / worked around:
- ebrelayer startup crashes (wrong base64 decode)
- connectivity to ports (using NodePort)
- missing DNS entries (grabbing IP/ports directly from kubectl)

Additional issues:
- [minikube] Missing init chain stuff in launch script
- [aws] Chain genesis outside of pod?
- [aws] GitHub action timing out despite deleting previous pipeline runs + using unique branch name

Lance is informed, said he would get back by EOD yesterday, but so far no feedback from him.

**Comment by pandaring2you** [comment]
Will proceed with developing Siftool (localnet) while above "Additional issues" are being resolved for tempnet.

**Comment by pandaring2you** [comment]
Blocked. Awaiting assistance from @lanerjo

**Comment by canercandan** [comment]
this is the current script I am using for creating pools on any environment:

```bash
#!/usr/bin/env bash

set -x

sifnoded tx clp create-pool \
  --from $SIF_ACT \
  --keyring-backend test \
  --symbol ceth \
  --nativeAmount 49352380611368792060339203 \
  --externalAmount 1576369012576526264262 \
  --fees 100000000000000000rowan \
  --node ${SIFNODE_NODE} \
  --chain-id $SIFNODE_CHAIN_ID \
  --broadcast-mode block \
  -y

sifnoded tx clp create-pool \
  --from $SIF_ACT \
  --keyring-backend test \
  --symbol cusdc \
  --nativeAmount 52798591956187184978275830 \
  --externalAmount 5940239555604 \
  --fees 100000000000000000rowan \
  --node ${SIFNODE_NODE} \
  --chain-id $SIFNODE_CHAIN_ID \
  --broadcast-mode block \
  -y

sifnoded tx clp create-pool \
  --from $SIF_ACT \
  --keyring-backend test \
  --symbol cusdt \
  --nativeAmount 1550459183129248235861408 \
  --externalAmount 174248776094 \
  --fees 100000000000000000rowan \
  --node ${SIFNODE_NODE} \
  --chain-id $SIFNODE_CHAIN_ID \
  --broadcast-mode block \
  -y

sifnoded tx clp create-pool \
  --from $SIF_ACT \
  --keyring-backend test \
  --symbol ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2 \
  --nativeAmount 200501596725333601567765449 \
  --externalAmount 708998027178 \
  --fees 100000000000000000rowan \
  --node ${SIFNODE_NODE} \
  --chain-id $SIFNODE_CHAIN_ID \
  --broadcast-mode block \
  -y

sifnoded tx clp create-pool \
  --from $SIF_ACT \
  --keyring-backend test \
  --symbol ibc/F279AB967042CAC10BFF70FAECB179DCE37AAAE4CD4C1BC4565C2BBC383BC0FA \
  --nativeAmount 32788415426458039601937058 \
  --externalAmount 139140831718 \
  --fees 100000000000000000rowan \
  --node ${SIFNODE_NODE} \
  --chain-id $SIFNODE_CHAIN_ID \
  --broadcast-mode block \
  -y

sifnoded tx clp create-pool \
  --from $SIF_ACT \
  --keyring-backend test \
  --symbol ibc/F141935FF02B74BDC6B8A0BD6FE86A23EE25D10E89AA0CD9158B3D92B63FDF4D \
  --nativeAmount 29315228314524379224549414 \
  --externalAmount 29441954962 \
  --fees 100000000000000000rowan \
  --node ${SIFNODE_NODE} \
  --chain-id $SIFNODE_CHAIN_ID \
  --broadcast-mode block \
  -y
```

along with some env variables:

```bash
export ADMIN_ADDRESS=""
export ADMIN_MNEMONIC=""
export SIF_ACT=admin
export SIFNODE_CHAIN_ID=sifchain-1
export SIFNODE_P2P_HOSTNAME=rpc.sifchain.finance
export SIFNODE_NODE=https://${SIFNODE_P2P_HOSTNAME}:443
```

**Comment by canercandan** [comment]
let me know if you need more inputs from my end thanks @pandaring2you

**Comment by pandaring2you** [comment]
Want to automatically create pools when tempnet is created. Need more documentation from chainops on how to customize tempnet.

**Comment by lanerjo** [comment]
Not sure what documentation you need. All the details are in the output at the tempnet deployment pipeline run.
The pipeline runs a script in the sifchain-devops repo, under scripts/tempnet/kubernetes directory, the script is what deploys/configures the network.

The purpose of Tempnet, is to be a vanilla environment, which deploys code from any sifnode branch, that a developer can then customize to suit their use case - by running scripts/commands after the deployment.

**Comment by pandaring2you** [comment]
Closing out. Less of a need for this in our current state. With the move to baremetal, we will need to think through how test tokens will be minted. @pandaring2you to note this down for ansible playbook in bare metal (have scripts/siftool for this, but need to specify bare metal target).
