### ISSUE TITLE
Review PR-2500 (Stuck-Txs tool)

### ISSUE THREAD

**Issue by marsifi** [Sifchain/sifnode#2501]
Review [PR 2500](https://github.com/Sifchain/sifnode/pull/2500) which adds the `ibc-diag stuck-txs` command to sifnoded.

This is the command we used to generate the list of stuck terra txs.

It could be reused in a monitoring tool, or whenever we need to generate a list of stuck txs

**Comment by joneskm** [comment]
Merged
