### ISSUE TITLE
Add peggy2 tests to Github action 

### ISSUE THREAD

**Issue by smartyalgo** [Sifchain/sifnode#2505]
- Add integration tests
- Add state machine tests
- Remove deprecated tests

**Comment by pandaring2you** [comment]
anytime anyone pushed to peggy2, peggy2 integration tests will run

**Comment by pandaring2you** [comment]
ETA EOD

**Comment by pandaring2you** [comment]
Realized additional revisions needed.

**Comment by pandaring2you** [comment]
James' multilock burn test currently does not pass

**Comment by pandaring2you** [comment]
@smartyalgo to create PR and merge changes

**Comment by pandaring2you** [comment]
est Tomorrow

**Comment by Brando753** [comment]
Breaking at unit test, having difficulty reproducing locally. Needs investigation.

**Comment by smartyalgo** [comment]
PR Created here 
https://github.com/Sifchain/sifnode/pull/2664

**Comment by pandaring2you** [comment]
Merged!
