### ISSUE TITLE
Peggy 2.0 Migration Scripts - Cosmos

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#2514]
Brando mentioned will probably need to work with Sifnode on this. Our point of contact will be Tanmay

From sprint planning meeting: https://docs.google.com/document/d/1kphqOOho7JEnfngsqHpDszYjUiusL-fiFCY8ub3FewY/edit#bookmark=id.j2d85us1h964

**Comment by pandaring2you** [comment]
@smartyalgo to work on execution with @Jedi2002

**Comment by pandaring2you** [comment]
Est. 1 week

**Comment by pandaring2you** [comment]
@juniuszhou - can you take a look at your old code for this and determine if it is still viable?

**Comment by juniuszhou** [comment]
I checked the migration code, it still works.

**Comment by Brando753** [comment]
Migration of Bank (denoms) and CLP will probably be assigned to @joneskm but he will need two weeks to get started on it.

**Comment by juniuszhou** [comment]
https://github.com/Sifchain/sifnode/pull/2688 created to handle the clp.

**Comment by pandaring2you** [comment]
Remainder of this task covered in https://app.zenhub.com/workspaces/current-sprint---engineering-615a2e9fe2abd5001befc7f9/issues/sifchain/sifnode/2420
