### ISSUE TITLE
Peggy 2.0 Load Testing: Sifchain -> EVM: Parallel locks and burns for erc20(usdt)/ethereum native (ETH,matic) tokens

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#2527]
- 1 cosmos sender x 1 token x many evm receivers (1k addresses for now),  1k tx per receiver

- 1 cosmos sender x many tokens (100 -> 1k -> 10k -> 100k) x 1 evm receiver

**Comment by pandaring2you** [comment]
@smartyalgo to add outline of test cases

**Comment by Brando753** [comment]
@juniuszhou has started on the second test "1 cosmos sender x many tokens (100 -> 1k -> 10k -> 100k) x 1 evm receiver". Check with @jzvikart to pair on this issue.

**Comment by pandaring2you** [comment]
@jzvikart - if you're blocked on 720, can you take a look at this with Junius?

**Comment by pandaring2you** [comment]
PR has been reviewed (tests written), should be able to merge today. @jzvikart will then run tests

**Comment by pandaring2you** [comment]
@jzvikart to check to see if we can run this test without geth

**Comment by pandaring2you** [comment]
@juniuszhou - are these tests complete?

**Comment by pandaring2you** [comment]
@juniuszhou to check with @jzvikart to see if we have a load test environment. Junius thinks we have these tests in the code base and will try to run them to see if they pass.

**Comment by juniuszhou** [comment]
It is not completed yet, I will resume the load testing for both cases.

**Comment by juniuszhou** [comment]
- 1 cosmos sender x 1 token x many evm receivers (1k addresses for now), 1k tx per receiver

create issue #3093 and pr #3094 to fix problems found during load testing. 

- 1 cosmos sender x many tokens (100 -> 1k -> 10k -> 100k) x 1 evm receiver

test running for a long time even for 100 tokens.

**Comment by juniuszhou** [comment]
fixed the #2977 with PR #3123.

**Comment by pandaring2you** [comment]
@jzvikart - do you have an outline of all the load testing and scenarios that have been written?
