### ISSUE TITLE
Write Group 2 Tests in Python

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2536]
- [x] Add support for IBC mocked tokens in Siftool
- [x] Test support for Rowan Lock/Burn (Sifchain/Ethereum)
- [x] Test support for IBC Lock/Burn (Sifchain/Ethereum)

**Comment by pandaring2you** [comment]
Rowan Lock/Burn works

**Comment by juniuszhou** [comment]
close it after pr merged.
