### ISSUE TITLE
Get denom from Ethereum LogBurn event

### ISSUE THREAD

**Issue by juniuszhou** [Sifchain/sifnode#2541]
For the cases like user burn rowan/ibc tokens on the Ethereum side, the denom can't be got from sifBridge + network id + contract. we need to get denom from events.

**Comment by pandaring2you** [comment]
has been reviewed, awaiting changes from junius

**Comment by pandaring2you** [comment]
Brando to make changes ETA EOD to merge

**Comment by juniuszhou** [comment]
close with pr merged.
