### ISSUE TITLE
Burning IBC Bridge Token from EVM side should use token's denom  

### ISSUE THREAD

**Issue by smartyalgo** [Sifchain/sifnode#2553]
This is a bug in ebrelayer, when trying to burn a bridgetoken to import it into sifchain. The burn will treat this as a native erc20 token, and assign a sifBridge<networkDescriptor><contractAddress> denom for the EthBridgeClaim, which would cause Sifchain to mint the wrong token on Cosmos side.

Deliverable:
- Verify this is indeed an issue
- Fix: The correct behavior is to use the denom stored on the contract itself, as emitted in the LogBurn evm event. 
- Any necessary unit, integration tests
- Update documentations

**Comment by banshee** [comment]
Fixed already.
