### ISSUE TITLE
Peggy 2 Smart Contracts Need to Support Cosmos Denom Lookups

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2567]
@juniuszhou identified that the Peggy 2 smart contracts for Bridge Tokens lookup Bridge Token address from the Token Address in the claim ignoring the network descriptor. This is a problem as EVM native assets use the Null address across multiple chains and would make the EVM assets fungible from the smart contracts point of view. The solution is to look up Bridge Token address from the Cosmos Denom and verify the Cosmos Denom is always set.

Assigned to whoever gets to it first.

**Comment by juniuszhou** [comment]
After the #2586 merged, the issue could be closed.

**Comment by banshee** [comment]
Code was already merged.
