### ISSUE TITLE
Review bridge architecture

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#2634]
End goal: Research on Peggy 3

**Comment by juniuszhou** [comment]
LockToDestination feature: If I want to transfer some eth from Ethereum to Binance, we need to lock it in smart contract, then burn it in sifnode side. We could add a new parameter in our lock function in bridge bank, user can choose the destination network and address. This way, Ethereum account can use sifnode to transfer token, even without sifnode account. Sifnode can work as token cross chain transfer hub.

**Comment by jprupp** [comment]
Reviewed Layer Zero, will review Axelar next.

**Comment by jprupp** [comment]
Interesting @juniuszhou, It's a good thing to put in the wishlist for the next version of Peggy, if we have one.
