### ISSUE TITLE
Review Elliot Sifnode Remediations Needed

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#2652]

**Comment by pandaring2you** [comment]
@juniuszhou to outline remaining issues:
EX. - In relayer code: How to set gas price and limit (non critical)

**Comment by juniuszhou** [comment]
continue working on it, already fork three new issues. # 2702 # 2726 and #2727

**Comment by pandaring2you** [comment]
@Brando753 to take a look at #2726 on junius's solution to keep address in memory.

**Comment by pandaring2you** [comment]
All remediations awaiting review

**Comment by pandaring2you** [comment]
@Brando753 to take a look at audit report and post remaining remediations needed.

**Comment by pandaring2you** [comment]
@Brando753 to outline TODOs via tickets

**Comment by pandaring2you** [comment]
Closing this out duplicate of issues#1642
