### ISSUE TITLE
Transaction error of ‘signature verification failed; please verify account number (7748), sequence (21977) and chain-id (sifchain-1): unauthorized’

### ISSUE THREAD

**Issue by pgoos** [Sifchain/sifnode#2670]
Repro steps TBA

**Comment by bksifchain** [comment]
@pgoos  - how did you get this error? What type of transaction? Can you pls provide more details

**Comment by pgoos** [comment]
@bksifchain this didn't come from me. I was pasting it from Casey's google doc after pmtp release. Think the issue can be closed as it seems no one is complaining about it anymore.
