### ISSUE TITLE
Set datadog alert for gas spikes (ETH transactions dropping due to low relayer balances)

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#2717]
There was a gas spike (ape coin?), and relayer balances were too low and had transactions rejected. 

Issue: https://github.com/Sifchain/Support-Tickets/issues/342 (Transactions need to be replayed by Brent. ) 

This won't be an issue in Peggy 2. 

Going forward: Set datadog alert on gas spikes

**Comment by intl-man** [comment]
Done:

https://app.datadoghq.com/monitors/70704455
