### ISSUE TITLE
If peggy support grpc gateway

### ISSUE THREAD

**Issue by juniuszhou** [Sifchain/sifnode#2727]
During reviewing the code, I found a "// TODO: Register grpc gateway". Seems the other x module defined the grpc like
    option (google.api.http).get = "/sifchain/clp/v1/pool/{symbol}";
Peggy team need to discuss it and to see if we should also add it.
If no, I will remove the todo.
If yes, need to implement it in protobuf file.

**Comment by pandaring2you** [comment]
resolved: not needed

**Comment by juniuszhou** [comment]
remove this todo via commit ab28ab28ba0112dd98c189c8c4605563974d430b.
