### ISSUE TITLE
Running this script gives an error at the end of the docker build:

### ISSUE THREAD

**Issue by utx0** [Sifchain/sifnode#278]
Running this script gives an error at the end of the docker build:

`=> exporting to image                                                                                                                                                     0.3s
 => => exporting layers                                                                                                                                                    0.3s
 => => writing image sha256:fec84c8f14c6a97d6c4559e6b7a5045a537bdbd1365e8f6ad62cda222ee3ec36                                                                               0.0s
 => => naming to docker.io/sifchain/sifnoded:localnet                                                                                                                      0.0s
ERROR: The Compose file '././genesis/docker-compose.yml' is invalid because:
services.sifnode2.networks.network_mode contains an invalid type, it should be an object, or a null
services.sifnode4.networks.network_mode contains an invalid type, it should be an object, or a null
======================
If one chooses the force kill remember to docker stop $(docker ps -aq) to spin down ganache-cli
======================`

_Originally posted by @ElliotFriedman in https://github.com/Sifchain/sifnode/pull/262#discussion_r523203167_

**Comment by utx0** [comment]
Hey guys, we are going to merge this due to a refactor that will change the name of the `build` directory to `deploy` as its more about deploying stuff and we want to do some UX cleanup before the next release. I have also created an issue from @ElliotFriedman comments above.

**Comment by ElliotFriedman** [comment]
With the new version of the deploy script I am not receiving this error

**Comment by jkbrooks** [comment]
@utx0 is this still an issue?  If so, please file with the standard format from the dev charter.  https://github.com/Sifchain/sifnode/issues/308 has an example.  We can then get it up on Gitcoin

**Comment by utx0** [comment]
Issues resolved by https://github.com/Sifchain/sifnode/pull/320
