### ISSUE TITLE
TODO more meaningfule name in instrumentation module

### ISSUE THREAD

**Issue by juniuszhou** [Sifchain/sifnode#2824]
"// TODO: rename, there isnt ethereumprophecyclaim, is there?"
"// TODO: Ambiguous naming"
Some events name in  instrumentation module not well named.

**Comment by pandaring2you** [comment]
Not necessary to fix. Remove TODO comment in a PR and explain reasoning.

**Comment by juniuszhou** [comment]
close it after #2920 merged.
