### ISSUE TITLE
TODO correct sifchain gas usage in relayer

### ISSUE THREAD

**Issue by juniuszhou** [Sifchain/sifnode#2829]
"// TODO this WithGas isn't correct
// TODO we need to investigate retries
// TODO we need to investigate what happens when the transaction has already been completed"

we need figure out the correct gas setting for sifndoe transaction.

**Comment by pandaring2you** [comment]
Not necessary to fix. Remove TODO comment in a PR and explain reasoning.

**Comment by banshee** [comment]
We should fix this by just making those amounts command-line options

**Comment by banshee** [comment]
See #2973 for the fix for this problem.
