### ISSUE TITLE
Cleanup witness/relayer debug logging

### ISSUE THREAD

**Issue by pandaring2you** [Sifchain/sifnode#2845]
cc @banshee @jzvikart @Brando753 

Note: This is a possible cause of the TPS rate dropping.

**Comment by pandaring2you** [comment]
lower pri. @jzvikart to add changes here as he sees them.

**Comment by jzvikart** [comment]
Possibly related: #2022

**Comment by jzvikart** [comment]
Using `--log_level error` on `ebrelayer` command line still emits events `DEBUG` and `INFO`.

**Comment by Brando753** [comment]
Assigned @banshee to fix this

**Comment by pandaring2you** [comment]
Jure: `ebrelayer init-witness` currently produces massive amounts of logs. Order of magniture is 30GB/h.

Most of the lines look completely useless:
```
{"L":"INFO","T":"2022-05-27T22:09:22.319+0200","C":"relayer/cosmos.go:203","M":"
claimtype cosmos.go: ","claimType: ":"unsupported"}
```
Size-wise these lines are still only ~10%, however.

@Brando753 @smartyalgo @banshee Can you confirm that the above can be removed? If so, I can try do do it myself.

@pandaring2you Since this ticket is currently assigned to @marshsif and `ebrelayer` is technically part of peggy, please co-assign and/or move it to a separate ticket as appropriate.

**Comment by pandaring2you** [comment]
@jzvikart to re-run tests to determine if TPS has increased since this has been now merged.

**Comment by pandaring2you** [comment]
Using --log_level error on ebrelayer command line still emits events DEBUG and INFO - James pushed this, should n be a blocker for load testing.

**Comment by smartyalgo** [comment]
Just merged the PR. https://github.com/Sifchain/sifnode/pull/2989 
Will no longer be an issue after redeploying
