### ISSUE TITLE
Handle Failure Condition on BurnLockEventToCosmosMsg

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2852]
Line 206 relayer/cosmos.go failures in call to BurnLockEventToCosmosMsg are not
retried, which would cause the relayer to need to be restarted in order to function.

**Comment by Brando753** [comment]
Error log created and code commented. Leaving open for second pass review of the condition.

**Comment by smartyalgo** [comment]
Agreed adding error logs and comment is the right approach. If `BurnLockEventToCosmosMsg` fails, maybe we should consider panic?

**Comment by Brando753** [comment]
Unsure, we need to huddle on this.
