### ISSUE TITLE
Remove use of BridgeRegistry

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2854]
The registry contract is used throughout the system to retrieve both the BridgeBank and CosmosBridge smart contract addresses. However, storing a reference to either BridgeBank or CosmosBridge will allow retrieval of the other smart contract address through the public getter methods on both contracts with the method cosmosBridge or bridgeBank on the opposite contracts. Remove BridgeRegistry from the codebase and use BridgeBank or CosmosBridge instead.

**Comment by juniuszhou** [comment]
Some code change for the registry.go was submitted. Now we have two variable to store both bridgeBank and cosmosBridge contract address in memory. There is no calling getter method to get other contract's address anymore in relayer. agree on won't fix it.

**Comment by pandaring2you** [comment]
@Brando753 @smartyalgo to huddle to confirm wont fix

**Comment by Brando753** [comment]
The team decided this is Won't Fix.
