### ISSUE TITLE
EthereumEventToEthBridgeClaim Validate Basic missing validation

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2863]
In cmd/ebrelayer/txs/parser.go on line 52 in function EthereumEventToEthBridgeClaim, there is a check that if the denom is eth, the claim type is a lock and the address isn’t 0, then the validation fails, however there is no logic for validating native currencies and other chains besides eth.

**Comment by smartyalgo** [comment]
https://github.com/Sifchain/sifnode/pull/2971
