### ISSUE TITLE
"Request body too large" in witness when locking large number of ERC20 tokens

### ISSUE THREAD

**Issue by jzvikart** [Sifchain/sifnode#2881]
After successfully locking 100k tokens on Ethereum side (with geth), only ~92600 made it to the destination sif wallet.

In witness.log:
```
{"L":"ERROR","T":"2022-06-04T14:53:35.130+0200","C":"relayer/ethereum.go:317","M":"failed to handle ethereum event.","errorMessage":"RPC error -32600 - Invalid Request: error reading request body: http: request body too large","S":"github.com/Sifchain/sifnode/cmd/ebrelayer/relayer.EthereumSub.CheckNonceAndProcess\n\t/.../cmd/ebrelayer/relayer/ethereum.go:317\ngithub.com/Sifchain/sifnode/cmd/ebrelayer/relayer.EthereumSub.Start\n\t/.../cmd/ebrelayer/relayer/ethereum.go:151"}
```
The witness seems to keep retrying in a loop, but nothing happens.

**Comment by pandaring2you** [comment]
@Brando753 @smartyalgo to review PR . Load test took ~6 hours before timing out

**Comment by jzvikart** [comment]
This is what was happening with `claimAmount`. According to @smartyalgo this is the number of entries in the same message):

![claimAmount.png](https://images.zenhubusercontent.com/614bf38fdd2ae43dbdd8672b/d59c1984-1633-4a18-a24f-3f7b3ee3e434)

**Comment by jzvikart** [comment]
Tried with @juniuszhou PR #2875 (with `MessagesInBatch = 5`), but it did not help. In fact, transactions now got stuck even sooner than before (after ~3400 tokens, previously. 92000). No change in the last 45 minutes. Overall, the throughput seems to be much lower.

I found this in the witness logs:
```
{"L":"ERROR","T":"2022-06-08T09:33:27.471Z","C":"relayer/ethereum.go:291","M":"failed to filter the logs from ethereum client","errorMessage":"websocket: read limit exceeded","S":"github.com/Sifchain/sifnode/cmd/ebrelayer/relayer.EthereumSub.CheckNonceAndProcess\n\t/.../cmd/ebrelayer/relayer/ethereum.go:291\ngithub.com/Sifchain/sifnode/cmd/ebrelayer/relayer.EthereumSub.Start\n\t/.../cmd/ebrelayer/relayer/ethereum.go:151"}
```

`geth` CPU usage is constantly around 200%.

**Comment by juniuszhou** [comment]
They are different issues. Without 2875, the relayer can get all events from geth, then send all claims in a sigle message. When the events number reachs several thousand, the relayer stops working because the data is too large.
After 2875 applied, relayer can avoid the previous problem. But relayer can't catch up the speed of block generation. Then relayer will query the events in multiple blocks. the returned events will be more and more until the data is too large for ethClient to get.

**Comment by jzvikart** [comment]
This is concerning because it means that the bridge can legitimately get stuck in a state in which it is not relaying any transactions and from which it cannot recover. This could be e.g. due to a DoS attack, but also due to peak in activity.

**Comment by smartyalgo** [comment]
When the rate is beyond capacity, the expected behavior is tx gets backed up, and queue size increases. However we should also see the queue gets consumed, and cleared eventually. 

Currently, our ethClient does have a way to limit # of blocks it fetches, set at 5000, which feels arbitrary
```
	maxQueryBlocks        = 5000

Reducing this number would help.

**Comment by jzvikart** [comment]
@smartyalgo IMO the bridge should not get stuck regardless of queue size. It should continue to process incoming transactions from the last one at the rate which equals the capacity of the bridge. This would mean that unless the rate of incoming transactions constantly exceeds the bridge capacity, all the transactions eventually get their turn.

**Comment by Brando753** [comment]
Lets huddle on this

**Comment by pandaring2you** [comment]
@smartyalgo @juniuszhou @Brando753 to sync on resolution
