### ISSUE TITLE
Unexpected behavior in BridgeBank multiLockBurn

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2884]
While burn() allows for the burning of tokens with an empty denom, _burnTokens() called by multiLockBurn() reverts with the same input

**Comment by Brando753** [comment]
Confirmed still in the current code base, we should verify these functions behave exactly the same.

**Comment by Brando753** [comment]
BridgeBank should NOT allow burns of empty string; Unit tests should be updated. SetCosmosDenom and like functions should revert if attempted to be set to an empty string.

**Comment by pandaring2you** [comment]
Significant amount of refactoring from javascript to typescript and treating erowan not being a bridgetoken . ETA tomorrow to have Elliot's remediations done by friday

**Comment by Brando753** [comment]
PR #2976 closes this issue out.

**Comment by Brando753** [comment]
This issue was also flagged by Certik audit:

# Description
In the `smart-contracts/contracts/BridgeBank/BridgeBank` contract, the `burn()` function does not check the token's denom while the validation of token denom is processed in the `_burnTokens()` function. The lack of handling token denom check may cause the denom to be an empty string in `LogBurn` event.

As a result, in the `x/ethbridge/keeper/keeper.go`, minting tokens will fail if the denom is an empty string.
```go
  case types.ClaimType_CLAIM_TYPE_BURN:
		coins = sdk.NewCoins(sdk.NewCoin(claim.CosmosDenom, claim.Amount))
		err = k.bankKeeper.MintCoins(ctx, types.ModuleName, coins)
```
# Recommendation
Recommend adding the validation for denom. For example:
```solidity
  require(keccak256(abi.encodePacked(denom)) != keccak256(abi.encodePacked("")), "INV_DENOM");
```
