### ISSUE TITLE
Mismatched Solidity Versions

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2885]
Contracts have matched Solidity versions; Blocklist.sol uses v0.5.16 while other contracts use 0.8.0. If compiled with a future version of the compiler, contracts may perform in unexpected ways.

**Comment by Brando753** [comment]
The Blocklist.sol contract is independent of the bridgebank/cosmosbridge contracts, not upgradeable, and already deployed on the Ethereum Network, so keeping the version number consistent with the deployed contract should allow better testing of contract interaction than compiling local copies differently from the deployed copy. Currently, ticket #3193 would rewrite the Blocklist contract to be more efficient, and that version should use the same version numbers; however, it is my opinion that this issue should be closed as not an issue. @smartyalgo or @juniuszhou please let me know if you concur or not so we can close this issue.

**Comment by smartyalgo** [comment]
Agreed. It is already deployed and non-upgradeable. This keeps it close to what we have in prod.
