### ISSUE TITLE
Unused IBridgeToken Interface

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2887]
The interface is unused. If additional BridgeToken methods such as Decimals() and Symbol() are added the interface could be used to simplify logic in BridgeBank.sol's getDecimals()/GetSymbol() method. Delete the unused interface or update it with the full set of BridgeToken methods and use it in BridgeBank.sol. If the interface is used, add the Apache-2.0 SPDX-License-Identifier as well.

**Comment by juniuszhou** [comment]
I prefer to delete the interface file. From the file name, it looks like the interface for bridge token, but token has its interface from openzeppelin. If we need define the interface for BridgeBank, we may add the IBridgeBank.sol implementation.

**Comment by juniuszhou** [comment]
create PR #3030 for it.
