### ISSUE TITLE
BridgeBank getBalance can be restricted to view

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2889]
Bridgebank getBalance function can be restricted to view.

**Comment by smartyalgo** [comment]
PR Available here https://github.com/Sifchain/sifnode/pull/3164

**Comment by Brando753** [comment]
Before this is closed a unit test or two should be added, I noticed there are no tests for this function on the smart contracts.

**Comment by Brando753** [comment]
closing the issue as getBalance is a private function and there is no clean way to support the unit tests for it without changing visibility.
