### ISSUE TITLE
Deprecated Items are unused yet maintained 

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2890]
BridgeBank.sol: 17-30, BridgeStorage.sol: 14- 17, 24-32, CosmosBankStorage.sol: 10-38. It's not clear why legacy variables marked 'DEPRECATED' are maintained. Remove the unused fields or add a comment explaining why they haven't been deleted.

**Comment by Brando753** [comment]
@juniuszhou @smartyalgo: this needs signoff from a second member before closing this as not an issue. Unless you think we should add a comment to the contracts?

**Comment by pandaring2you** [comment]
cc @smartyalgo

**Comment by smartyalgo** [comment]
Agreed, signing off. I think it's nice to add comment, not necessary. Closing
