### ISSUE TITLE
CLP has Unused Permissions

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2891]
The clp module is given unused authtypes app/app.go: 158. Burner permission. Module account burning permission should be assigned only when required by internal module operations. Enabling a module account to modify coin balances inappropriately is a security risk as it increases the likelihood of introducing code that incorrectly modifies on-chain balances. Remove the unused burner permissions.

**Comment by smartyalgo** [comment]
Confirmed this is still an issue

**Comment by smartyalgo** [comment]
Talked to Kevin Jones, 
As of release v0.13.4
Burn is used here https://github.com/Sifchain/sifnode/blob/c7cfe3f4ac7363ff4918510590c082954e0ef026/x/clp/keeper/rewards.go#L108
Mint is used here https://github.com/Sifchain/sifnode/blob/c7cfe3f4ac7363ff4918510590c082954e0ef026/x/clp/keeper/rewards.go#L54

Those permissions are required for CLP

**Comment by juniuszhou** [comment]
If CLP really need both permissions, shoule we just close this issue? @Brando753 @smartyalgo

**Comment by pandaring2you** [comment]
@smartyalgo reached out to KevinJ - both permissions are required. Fix not needed. @Brando753 or @banshee to have final vote on sign off.

**Comment by banshee** [comment]
Agreed, no fix needed.

**Comment by juniuszhou** [comment]
close it after @banshee agreed no fix.
