### ISSUE TITLE
Dispensation module has unused burning permissions

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2892]
The dispensation module is given unused authtypes app/app.go: 159. Burner permission. Module account burning permission should be assigned only when required by internal module operations. Enabling a module account to modify coin balances inappropriately is a security risk as it increases the likelihood of introducing code that incorrectly modifies on-chain balances. Remove the unused burner permissions.

**Comment by banshee** [comment]
https://github.com/Sifchain/sifnode/pull/3015 exists, but we may want to put the commit in a different branch

**Comment by pandaring2you** [comment]
@khdegraaf - whats the process for merging this into master (#3015)?

**Comment by khdegraaf** [comment]
Get two reviews, then I or another admin can merge it (I won't normally otherwise unless it is test only code)

**Comment by smartyalgo** [comment]
@khdegraaf two reviews are in, good to merge

**Comment by pandaring2you** [comment]
PR goes to master, waiting on Kevin or Caner to merge
