### ISSUE TITLE
Potential Chain Halt due to improper msg validation | MSR-01 Panic Attack for Invalid Network Descriptor

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2893]
It may be possible to halt the chain by submitting an EthBridgeClaim msg with an invalid NetworkDescriptor and nonce = 0 : x/ethbridge/types/claim.go: 88-90. The NetworkDescriptor is not checked by msg.ValidateBasic() and is passed to the CreateEthBridgeClaim function. Even though GetEthereumLockBurnSequence will return a value of 0 due to the unrecognized NetworkDescriptor, a nonce of 0 will pass the validation check on line 217 of msg_server.go. If srv.Keeper.ProcessClaim() and srv.KeeperProcessSuccessfulClaim() complete successfully with the invalid NetworkDescriptor, it may result in a panic when src.Keeper.AddTokenMetadata() is called on line 243. Explicitly check that the NetworkDescriptor is valid in MsgCreateEthBridgeClaim's ValidateBasic function.

**Comment by juniuszhou** [comment]
We can maintain a valid network descriptor list, then use it to check if network descriptor is valid. To update the list, we may need a special transaction with authority. It will make the solution complicated. The simpler solution is to add the error as return value from AddTokenMetadata, to avoid the panic.

**Comment by pandaring2you** [comment]
PR submitted, in review

**Comment by banshee** [comment]
PR #3014 submitted

**Comment by banshee** [comment]
PR merged.  Added issue  #3066 to track adding integration tests.
