### ISSUE TITLE
Genesis state fields not properly validated

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2895]
The function doesn't validate that the CrosschainFeeReceiveAccount is a valid Bech32 address, but InitGenesis will panic if the address is invalid. Validate that data.CrosschainFeeReceiveAccount is a valid Bech32 address in the ValidateGenesis() method to catch invalid addresses. If the correct default genesis state is an empty field and the updated validation method rejects the module's default genesis state, consider adding an exception such that an empty CrosschainFeeReceiveAccount value passes validation. Alternatively, consider using a default constant sdk.AccAddress variable for the default value.

**Comment by juniuszhou** [comment]
close it after #3007 merged.
