### ISSUE TITLE
CLP module params query not implemented

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2900]
File(s) affected: x/clp/client/cli/query.go: 17-38, 123, x/clp/client/rest/query.go: 17-38, x/clp/keeper/grpc_query.go, x/clp/keeper/querier.go: 12-34. Clp module's get params query is not implemented, but module parameters must be queriable by users of the chain for transparency. Implement the GetParams() querier method and register the query route on the module.

**Comment by juniuszhou** [comment]
it is already fixed in future/peggy2. GetParams added in query.go

**Comment by pandaring2you** [comment]
Won't fix. @smartyalgo or @Brando753 to confirm

**Comment by juniuszhou** [comment]
fixed via code merge from develop branch, and commit is 4f5671359.
