### ISSUE TITLE
Use constants in clp query

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2902]
Affected file: x/clp/client/cli/query.go: 123. Default string "ClpAdmin" is constant, but is not defined as a constant variable. Consider using a constant variable for "ClpAdmin" as input to authypes.NewModuleAddress().

**Comment by juniuszhou** [comment]
there is no "ClpAdmin" variable in query.go since admin x module introduced. the admin just in the genesis and the default value set as  authypes.NewModuleAddress()

**Comment by pandaring2you** [comment]
Won't fix. @smartyalgo @Brando753 to confirm

**Comment by smartyalgo** [comment]
Agreed, no longer an issue.

**Comment by banshee** [comment]
Agreed, close as obsolete.
