### ISSUE TITLE
Should use custom error type in tokenregistry

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2905]
File: x/tokenregistry/types/msgs.go: 178-184. Empty 'Name' and 'Symbol' fields on Metadata return ErrInvalidAddress, but neither is type sdk.AccAddress. Create additional custom error types ErrInvalidMetadataName, ErrInvalidMetadataSymbol and return them instead of ErrInvalidAddress.

**Comment by juniuszhou** [comment]
PR #3011 to fix it.

**Comment by juniuszhou** [comment]
close it after #3011 merged.
