### ISSUE TITLE
Non-sequential ordering of protobuf fields

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2906]
File: proto/sifnode/tokenregistry/v1/types.proto: 36-37. While in general proto messages will serialize correctly, protobuf encoding library implementations may vary. Follow best practices by setting permissions = 14 and decrement the following message fields accordingly.

**Comment by Brando753** [comment]
This is most likely because fields were removed/changed and protobufs require the ordering numbers to be preserved. While technically during a chain upgrade we could patch them to an entirely new ordering it may not be worth considering. I do want at least one other persons opinion before I close this as wont fix. @banshee  @smartyalgo @juniuszhou?

**Comment by juniuszhou** [comment]
It is better to keep the 14 as reserved. I prefer won't fix it.

**Comment by juniuszhou** [comment]
won't fix it since no one against it
