### ISSUE TITLE
Oracle module overwrites reserved error code

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2908]
Affected file x/oracle/types/errors.go: 9. ErrInvalidEthNonce breaks with best practices by using reserved error code 1. Any error that does not contain ABCICode information is categorized as an error with code 1, a reserved error code that is kept open upstream in the Cosmos SDK (see types/errors/errors.go). To keep the module's custom errors identifiable by their error codes, start error code ordering at 2.

**Comment by juniuszhou** [comment]
The PR #2926 is ready for review.

**Comment by banshee** [comment]
PR merged.
