### ISSUE TITLE
Failed transactions not properly handeled

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2915]
File: ebrelayer/txs/relayToCosmos.go: 58-67, 80-100. Failed transactions are not properly handled. If anything unexpected occurs (address is out of rowan for fees, incorrectly structured transaction, misconfigured connection, etc.) the transaction is dropped and not relayed. Implement a module for sending, monitoring, and retrying Cosmos SDK transactions using cliCtx.BroadcastMode Async. Async is non-blocking, enabling the relayer to continue normal operations while the transaction hash and relevant information is passed to a retry module which processes the transaction. For common Tendermint and common Sifnode errors the retry module should be able to adjust and retry transactions. If a transaction is unable to be completed, consider using panic() depending on the severity of the error; for example, if the relayer cannot pay gas then it should send a request for funds to a faucet and/or shut down.

**Comment by banshee** [comment]
+1 to Junius's comment.  We don't need or want to retry individual transactions as they happen; if one fails to go through, it'll be handled the next time the relayer tries to relay a transaction.
