### ISSUE TITLE
Insufficient transaction retry backoff time

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2916]
File: ebrelayer/txs/relayToEthereum.go: 169-187. We attempt to fetch the transaction receipt 60 times with one second in between attempts. During periods of high network congestion, this may be insufficient and result in a failure to submit the transaction, resulting in the premature termination of batch prophecy processing. Consider a backoff query approach such that each successive attempt waits longer than the one before it. For a linear backoff, replace sleepThread(1) with sleepThread(i). We recommend using sleepThread(i*i) for an exponential backoff. In future versions, consider querying the network's estimated confirmation time and adjusting the backoff accordingly.

**Comment by Brando753** [comment]
Time has since been increased to 2 seconds but should be exponential backoff instead. Leaving this open for that patch.

**Comment by juniuszhou** [comment]
close it after #3017 merged.
