### ISSUE TITLE
Use constant variable for GRPC endpoint 

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#2917]
Files: ebrelayer/relayer/cosmos.go: 336, ebrelayer/relayer/prophecyHandler.go: 164, ebrelayer/relayer/ethereum.go: 474. 

Constant GRPC endpoint is hardcoded, but not designated as a constant variable. The default GRPC endpoint may change in the future. Use a constant variable to define the GRPC endpoint url.

**Comment by smartyalgo** [comment]
GRPC endpoints are now using values stored in sub. No longer an issue

**Comment by smartyalgo** [comment]
Please confirm and close ticket
@banshee @juniuszhou @Brando753

**Comment by juniuszhou** [comment]
yes, it is not an issue and close it.
