### ISSUE TITLE
Peggy2: relayers are constantly looking at cosmos from block 0

### ISSUE THREAD

**Issue by banshee** [Sifchain/sifnode#2937]
fromBlockNumber never increases; we're always looking from block 0:

{"level":"info","ts":1655157683.8121085,"caller":"relayer/cosmos.go:174","msg":"ProcessLockBurnWithScope","globalSequence":9,"fromBlockNumber":0,"toBlockNumber":145}

I suspect there's a problem with GetGlobalSequenceBlockNumberFromCosmos

**Comment by juniuszhou** [comment]
I checked the issue in my local, the fromBlockNumber will be updated if we have lock/burn transaction in sifnode.

**Comment by juniuszhou** [comment]
{"level":"info","ts":1655174125.06718,"caller":"relayer/cosmos.go:174","msg":"ProcessLockBurnWithScope","globalSequence":3,"fromBlockNumber":55,"toBlockNumber":66}

**Comment by juniuszhou** [comment]
close it after #2940 merged.
