### ISSUE TITLE
[ChainOps]: REST LCD (1317) Endpoint CORS

### ISSUE THREAD

**Issue by 59023g** [Sifchain/sifnode#298]
UI needs this to test our deployment against Testnet. This is blocking.

Wildcard ("*") would be ideal for now as it would allow us to test in a variety of environments and dynamically generated domains. 

But, if you need a specific URL, please contact me directly. I will share our static testnet deployment URL.

Cosmos-sdk on CORs: https://docs.cosmos.network/master/interfaces/rest.html#cross-origin-resource-sharing-cors

**Comment by utx0** [comment]
The cors fix was applied here: https://github.com/Sifchain/sifnode/pull/302

**Comment by utx0** [comment]
Let us know if this solves this issue for now @59023g

**Comment by 59023g** [comment]
Is this live? I don't see `Access-Control-Allow-Origin: *` header in response.
