### ISSUE TITLE
[ChainOps]: REST LCD (1317) Endpoint HTTPS 

### ISSUE THREAD

**Issue by 59023g** [Sifchain/sifnode#299]
UI needs this to test our deployment against Testnet. 

As far as blocking: We may be able to get away with forcing it on the client side. Not sure. This is related to CORS issue: https://github.com/Sifchain/sifnode/issues/298

**Comment by utx0** [comment]
If you can force this for now that would be super.

**Comment by 59023g** [comment]
> If you can force this for now that would be super.

Experimenting with now. Should have an answer EOD. 
Also, if there's a proxy service or other ways around this that I can control I'm all ears

**Comment by utx0** [comment]
This has been resolved and push to all env's
