### ISSUE TITLE
Fix false negative tests

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#3002]
Some of the original smart contract unit tests were passing when they should not have, these tests originally written in javascript are being converted to typescript and fixed.

**Comment by Brando753** [comment]
This ticket has also been used to upgrade most of our tests to typescript rather then javascript and update how some of the test fixtures are working, progress is being tracked here:

- [X] test/test_bridgeBankLock.ts
- [X] test/testBridgeBank.ts
- [X] test/test_randomtTrollToken.ts
- [X] test/test_UnicodeToken.ts
- [X] test/test_CommissionToken.ts
- [X] test/testCosmosBridge.ts
- [X] testFixture.ts
- [X] denoms.ts
- [ ] test_failHardToken.js 
- [ ] test_ibcTokenExport.js
- [ ] test_manyDecimalsToken.js
- [ ] test_security.js
- [ ] testSignatureAggregationSecurity.js
- [ ] test_txSignatureAggregation.js
- [ ] test_upgradeContracts.js
- [ ] test_valset.js

**Comment by pandaring2you** [comment]
Expected to close this and dependent task out by tomorrow

**Comment by Brando753** [comment]
PR #2976 Closes this out.
