### ISSUE TITLE
[Peggy] Bridge Transactions from ethereum to sifchain overflow

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#303]
Currently Peggy overflows when too large of a transfer happens from ethereum to sifchain. This issue was caught when trying to transfer 10000000000000000000 wei from ethereum to sifchain. Will need to change the number type on cosmos for how this is stored, or we could possible divide on the ethereum side before emitting and then multiply out when going the other way.

**Comment by ElliotFriedman** [comment]
Drilling down on where this problem is in the codebase, when querying initial accounts created locally, balances are 1e34 so this is not likely an issue with cosmos storing a users balance and more likely that in the relayer we are not using a proper uint256 or big number library.

**Comment by kingpinXD** [comment]
If the issue is from the Sifnode side, using a Sdk.uint as the datatype should solve it. This is a wrapper over go's big.int

**Comment by jkbrooks** [comment]
@ElliotFriedman please reformat in the standard bug filing format so we can get Gitcoin on this.  Check out https://github.com/Sifchain/sifnode/issues/308 and the Development Charter for more context
