### ISSUE TITLE
Add integration tests for invalid network descriptors

### ISSUE THREAD

**Issue by banshee** [Sifchain/sifnode#3066]

**Comment by banshee** [comment]
See pr #3014

**Comment by banshee** [comment]
https://github.com/Sifchain/sifnode/pull/3067

**Comment by pandaring2you** [comment]
Since we'll be using trusted witnesses for the near-mid future, can defer to peggy 2.x (when we decentralize ebrelayer witnesses)

**Comment by banshee** [comment]
PR merged.
