### ISSUE TITLE
COS-01 | Missing Error Handling

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#3077]
This bug has been worked on before, I cannot find the original ticket. The commit that discusses this is commit `135d169883d73fc1573591d337941265ce93d1e6` as part of PR #2639 lets verify this has been fixed then close it out.

# Description
In the `cmd/ebrelayer/relayer/cosmos.go`, the `ProcessLockBurnWithScope()` function parses the transaction log into events and generates `Lock/Burn` messages depending on the type and data of the event.

```go
  for _, event := range txLog.Events {
    claimType := getOracleClaimType(event.GetType()) 
    sub.SugaredLogger.Infow("claimtype cosmos.go: ", "claimType: ", claimType)
    switch claimType {
      case types.MsgBurn, types.MsgLock:
        cosmosMsg, err := txs.BurnLockEventToCosmosMsg(event.GetAttributes(), sub.SugaredLogger)
        if err != nil {
          sub.SugaredLogger.Errorw("sifchain client receive a malformed burn/lock message.",
  			errorMessageKey, err.Error())
  			/**
  			TODO: This continue would cause the bridge to be stuck.
  			This is same as skipping a msg, the next cosmosMsg.GlobalSequence
  			will be +2 of current global sequence,
  			*/
  			continue 
        }
        ...
    }
  }
```
According to the design, whenever a user burns or locks the asset, the `GlobalSequence` of the transaction will increase by 1 automatically. After the verification node processes the transaction, the `WitnessLockBurnNonce` of the verification node will also automatically increase by 1.

Under normal circumstances, `WitnessLockBurnNonce+1 == GlobalSequence`, ensures that transactions are executed in order and avoid being repeatedly executed. When an error occurs, the `WitnessLockBurnNonce` of the verification node should be processed to ensure that when an error occurs in a transaction, subsequent transactions can be executed normally.

However, when the creation of the message fails, the function does not handle the error but skips the event directly, and the value of `GlobalSequence` will not be incremented. It may cause the relayer to get stuck and be unable to process transactions.

# Recommendation
The auditing team recommend adding the error handling logic in `ProcessLockBurnWithScope()` function.

**Comment by juniuszhou** [comment]
The comments as follows explained why don't handle the error and discontinue with next event from Ethereum.
/*
When fail to parse the event data, only thing relayer can do just skip it.
If the wrong event's global sequence is not we expected, then no impact for relayer
to process next event. But if glocal sequence is next one,
this continue would cause the bridge to be stuck, since sifnode requires each relayer
strictly submit the prophecy according to global sequence
This is same as skipping a msg, the next cosmosMsg.GlobalSequence
will be +2 of current global sequence. then only solution is upgrade the relayer to
the version can handle this specific event.
*/

**Comment by juniuszhou** [comment]
won't fix and close it after another confirmation from @Brando753 @smartyalgo or @banshee

**Comment by smartyalgo** [comment]
Agreed won't fix. 
In an ordered bridge design, ebrelayer cannot handle when the cosmos event is malformed. It will retry the tx of that GlobalSequence. This is mitigated by implementing `ValidateBasic` for `MsgLock` and `MsgBurn` such that the cosmosMsg wont be malformed.
