### ISSUE TITLE
Peggy is Allowed to Burn when it should lock and vise versa

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#311]
A current problem we face in peggy on the relayer and cosmos side is that you can burn an asset that is cosmos native, which will not trigger correct logic on the ethereum side. Say you have some rowan on sifchain, if you burn that rowan, instead of locking it, it will try to unlock rowan on the ethereum side instead of trying to mint it. This will effectively mean that money was destroyed unless an admin steps in and mints tokens for you.

**Comment by juniuszhou** [comment]
We also need avoid the locking the pegged eth/erc20 in Sifchain. The question is how to distinguish the native asset and pegged asset. Pegged symbol start with prefix 'c', but the native symbol may also start with 'c'. Or we have the list of pegged token.

**Comment by ElliotFriedman** [comment]
We may have to end up keeping a list of pegged tokens and non pegged tokens via a mapping of symbols to booleans.

**Comment by caseyturnerarrington** [comment]
We could move forward with hardcoding tokens that start with 'c'. This would be an ONLY alphanet solution and we should come back to it at a later date to adjust this as we incorporate more tokens.

**Comment by ElliotFriedman** [comment]
Fix has been merged. Closing

**Comment by ElliotFriedman** [comment]
Fixed in this PR: https://github.com/Sifchain/sifnode/pull/408
