### ISSUE TITLE
HAE-01 | Incomplete of Handler for Messages in `x/tokenregistry`

### ISSUE THREAD

**Issue by Brando753** [Sifchain/sifnode#3168]
Affected Files: handler.go L17

# Description
In the `x/tokenregistry` module, the admin can submit messages with the types `MsgRegisterAll` and `MsgDeregisterAll` via CLI commands. Also, functions accepting parameters with types `MsgRegisterAll` and `MsgDeregisterAll` can be found in x/tokenregistry/handler/msg_server.go. However, these two types of messages are not handled in x/tokenregistry/handler/handler.go.

# Recommendation
Recommend adding handlers for corresponding message types, or removing deprecated logic in the module.

**Comment by juniuszhou** [comment]
close it after #3179 merged.
