### ISSUE TITLE
[Peggy] Build issue: always check the return value from system() call in rakefiles

### ISSUE THREAD

**Issue by banshee** [Sifchain/sifnode#318]
**Describe the bug**

Should always check the result of system() in rakefiles.  We do check sometimes by doing ```system("...") or exit 1``` but that should always be the way we call system().

Probably should add something like a system_or_exit() call to deploy/rake/helpers.rake that always checks the return value and prints a useful error.

(Not checking the return value means you can easily get into an unexpected state, since we just assume things worked.)

**Bug Reproduction Steps**

Set up your environment so that command lines executed by system() don't have the right tools installed.

**Comment by banshee** [comment]
PR #320 added some support for this - there's now a safe_system() method available that exits on a non-zero return from a system call.  Not all rake files have been converted to use this though.

**Comment by caseyturnerarrington** [comment]
Per James, closing
