### ISSUE TITLE
[Peggy] Static Analysis (Med) - Reentrancy in CosmosBridge.newProphecyClaim

### ISSUE THREAD

**Issue by EddCS** [Sifchain/sifnode#322]
[`Slither`](https://github.com/crytic/slither/) raised a medium warning about a potential reentrancy vulnerability in [`CosmosBridge.newProphecyClaim`](https://github.com/Sifchain/sifnode/blob/develop/smart-contracts/contracts/CosmosBridge.sol#L129) and suggested implementing the [`Checks-Effects-Interactions`](https://docs.soliditylang.org/en/v0.4.21/security-considerations.html#re-entrancy) pattern to circumvent this. 

```
INFO:Detectors:
Reentrancy in CosmosBridge.newProphecyClaim(CosmosBridgeStorage.ClaimType,bytes,uint256,address,string,uint256) (CosmosBridge.sol#129-199):
        External calls:
        - tokenAddress = BridgeBank(bridgeBank).createNewBridgeToken(symbol) (CosmosBridge.sol#156)
        State variables written after the call(s):
        - usedNonce[_prophecyID] = true (CosmosBridge.sol#192)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#reentrancy-vulnerabilities-1
```
If this is decided to not be an issue then I can add a filter to remove it from future static analysis runs.

**Comment by stbeyer** [comment]
False positive, since it  calls trusted code.

**Comment by EddCS** [comment]
Okay, I've added this specific warning to the slither triage config file so it won't appear on future runs.

**Comment by khdegraaf** [comment]
This has been fixed in slither config.
