### ISSUE TITLE
[Peggy] Static Analysis (High) - State variable shadowing in BridgeBank

### ISSUE THREAD

**Issue by EddCS** [Sifchain/sifnode#323]
Slither raised a high severity warning about state variable shadowing of `BridgeBank_initialized` and its parent contracts `CosmosWhiteList_initialized` and `EthereumWhiteList._initialized`. 

```
INFO:Detectors:
BridgeBank._initialized (BridgeBank/BridgeBank.sol#27) shadows:
        - CosmosWhiteList._initialized (BridgeBank/CosmosWhiteList.sol#11)
        - EthereumWhiteList._initialized (BridgeBank/EthereumWhitelist.sol#9)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#state-variable-shadowing
```
If this is decided to just be noise we can change `slither` to ignore this error in the future.

**Comment by stbeyer** [comment]
This is a side effect of the upgradability pattern. I think it's a false positive

**Comment by EddCS** [comment]
Okay, I've added this specific warning to the slither triage config file so it won't appear on future runs.

**Comment by khdegraaf** [comment]
this has been fixed in slither config.
