### ISSUE TITLE
[Peggy] Static Analysis (Med) - State variable shadowing from abstract contracts in BankStorage

### ISSUE THREAD

**Issue by EddCS** [Sifchain/sifnode#324]
`Slither` raised a medium severity warning about state variable shadowing from abstract contracts. [`BridgeBank/BankStorage`](https://github.com/Sifchain/sifnode/blob/develop/smart-contracts/contracts/BridgeBank/BankStorage.sol#L35) shadows `___gap` variables in [`CosmosWhiteListStorage`](https://github.com/Sifchain/sifnode/blob/develop/smart-contracts/contracts/BridgeBank/CosmosWhiteListStorage.sol#13), [`EthereumBankStorage`](https://github.com/Sifchain/sifnode/blob/develop/smart-contracts/contracts/BridgeBank/EthereumBankStorage.sol#23), and [`CosmosBankStorage`](https://github.com/Sifchain/sifnode/blob/develop/smart-contracts/contracts/BridgeBank/CosmosBankStorage.sol#39).

```
INFO:Detectors:
BankStorage.____gap (BridgeBank/BankStorage.sol#35) shadows:
        - CosmosWhiteListStorage.____gap (BridgeBank/CosmosWhiteListStorage.sol#13)
        - EthereumBankStorage.____gap (BridgeBank/EthereumBankStorage.sol#23)
        - CosmosBankStorage.____gap (BridgeBank/CosmosBankStorage.sol#39)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#state-variable-shadowing-from-abstract-contracts
```

If this is decided to not be an issue then I can add a filter to remove it from future static analysis runs.

**Comment by ElliotFriedman** [comment]
We probably have to make these variables private. Turns out this is a real issue slither caught.

**Comment by stbeyer** [comment]
Since it's just a gap, it doesn't really matter too much but making it private should get rid of the issue.

**Comment by EddCS** [comment]
`___gap` is already a private variable in all four files.

**Comment by ElliotFriedman** [comment]
If it's already private, it doesn't matter their names are the same since they wont be available in inherited files.

**Comment by EddCS** [comment]
Okay, in which case I'll add these to the slither config so the warning isn't raised again.

**Comment by khdegraaf** [comment]
This has been fixed in slither config.
