### ISSUE TITLE
[Peggy] Static Analysis (Med) - CosmosBridge.newProphecyClaim is an uninitialized local variable 

### ISSUE THREAD

**Issue by EddCS** [Sifchain/sifnode#325]
`Slither` raised a medium severity warning that [`CosmosBridge.newProphecyClaim`](https://github.com/Sifchain/sifnode/blob/develop/smart-contracts/contracts/CosmosBridge.sol#L129) is an uninitialized local variable. 

```
INFO:Detectors:
CosmosBridge.newProphecyClaim(CosmosBridgeStorage.ClaimType,bytes,uint256,address,string,uint256).tokenAddress (CosmosBridge.sol#142) is a local variable never initialized
CosmosBridge.newProphecyClaim(CosmosBridgeStorage.ClaimType,bytes,uint256,address,string,uint256).symbol (CosmosBridge.sol#143) is a local variable never initialized
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#uninitialized-local-variables
```
If this is decided to not be an issue then I can add a filter to remove it from future static analysis runs.

**Comment by stbeyer** [comment]
Slither recommends local variables to always be explicitly initialized. We usually treat this as a false positve

**Comment by khdegraaf** [comment]
@ElliotFriedman and @stbeyer do you believe this to be a false positive in this instance?

**Comment by stbeyer** [comment]
yes, it's a false positive, because it is assigned in 2 out of 3 branches in the code and the third one reverts. 
Slither is opinionated here in that it recommends always initializing this type of variable to 0 explicitly, instead of relying on the default values (which is address(0)). 
I personally don't agree with this, since default values are clearly defined for all variable types in Solidity.

**Comment by EddCS** [comment]
> I personally don't agree with this, since default values are clearly defined for all variable types in Solidity.

Based on this, I'll exclude `uninitialized-local` detector warnings in the slither config file. That will prevent this warning appearing in the future.

**Comment by khdegraaf** [comment]
Are uninitialized-local detections always wrong, or just usually wrong?

**Comment by khdegraaf** [comment]
This has been fixed in Slither config.
