### ISSUE TITLE
HAL-07 downcasting of 64-bit integer

### ISSUE THREAD

**Issue by juniuszhou** [Sifchain/sifnode#3258]
# Description
It has been observed that some strings are being converted to their integer representation. The strconv.Atoi() function will convert strings to base 10 integers using either 32 bytes or 64 bytes, depending on the operating system running the code.
It is important to carefully trace the values converted in this way and to ensure that they remain at the same level of precision. For example, a 64-bit system should avoid downcasting an integer representation that uses a smaller number of bits. Downcasting in this way can cause integer overflows/underflows which could result in subtle logic errors.

Code Location:
```
x/ethbridge/client/cli/query.go, Line 161
Listing 10
161 globalSequence , err := strconv.Atoi ( args [1])
x/ethbridge/client/cli/query.go, Line 200
Listing 11
200 globalSequence , err := strconv.Atoi ( args [1])
x/ethbridge/client/cli/tx.go, Line 188
Listing 12
188 power , err := strconv . Atoi ( args [2])
x/ethbridge/client/rest/rest.go, Line 357
Listing 13
357 globalSequence , err := strconv.Atoi ( restSequence )
```

# Recommendation
Ensure that all integer values are downcasted according to their expected usage. Avoid reducing the precision of values.
Consider using strconv.ParseInt() to specify a bit of length manually.

**Comment by juniuszhou** [comment]
According to the go doc, `Atoi is equivalent to ParseInt(s, 10, 0)`. I don't see there is necessity to use ParseInt. We can close it after one more agreement from @Brando753 @smartyalgo @banshee

**Comment by smartyalgo** [comment]
So the issue is:
AtoI outputs int32/int64 depending on the machine. 
This could be an issue if downstream expects int32, and we're passing int64
e.g. 
In cli/tx.go 
```
func GetCmdUpdateWhiteListValidator() *cobra.Command {
...
188 power , err := strconv . Atoi ( args [2])
```
power is type int, aka int64 depending on the machine. Later on, it is cast as uint32 to updateWhiteListValidator, thus downcasting. 

ParseInt returns an err, which will tell us when string input is out of range, thus preventing input beyond int32 range
```
	var power64string string = "9223372036854775807"

	power32, err := strconv.ParseInt(power64string, 10, 32)
	if err != nil {
		fmt.Println("Errored", err)
	}
	fmt.Println(power32)

```
Gives 
```
Errored strconv.ParseInt: parsing "9223372036854775807": value out of range
2147483647
```

**Comment by juniuszhou** [comment]
I agree, ParseInt can avoid this downcasting error. will create a PR to fix it.

**Comment by juniuszhou** [comment]
close it after #3287 merged.
