### ISSUE TITLE
HAL-14 unused variables 

### ISSUE THREAD

**Issue by juniuszhou** [Sifchain/sifnode#3262]
# Description
It was found that the entry variable that is declared in GetTokenMetaData is never used within the function.

Code Location:
```
x/tokenregistry/keeper/metadata.go, Lines 32
Listing 25
32 entry , err := k.GetRegistryEntry (ctx , denomHash )
```

# Recommendation
It is recommended to remove any unused variables from the code base.

**Comment by juniuszhou** [comment]
Checked the code, actually both entry and err used later. I suggest we won't fix it. Close it after one more confirmation

**Comment by smartyalgo** [comment]
Confirmed, closing.
