### ISSUE TITLE
[Peggy] Dropped Transactions

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#328]
A current hypothetical problem that we face in peggy is that if a validator goes offline and misses a transaction, they will not listen to the events that happened in the past and submit an oracle claim based on it. We need a solution where we can replay previous transactions, listen to their events, and submit transactions based on this.

This solution should work for both ethereum and cosmos transactions in case a listener drops tx's on either side.

**Comment by utx0** [comment]
Yeah the current solution only works in real time. However why would you want to reply events? Really if a validator goes off line we should have one a BFT type system so it doesnt matter and two the validator should get slashed and effert their block rewards.

**Comment by ElliotFriedman** [comment]
This was brought up in a discussion with @musnit where we were discussing what happens in a scenario where multiple validators are offline.

**Comment by utx0** [comment]
yeah i get that. However I think it would be easier to just make the system more BFT and be totally ok with faults and avoid complex retry logic.

**Comment by musnit** [comment]
it is still valuable to have retry/catchup logic even if the system is BFT.

also, we can't launch production without handling dropped connections. making the system BFT or collateralized/insured is way more work than just adding a retry/catchup - i don't really get where you're coming from @utx0

**Comment by musnit** [comment]
@ElliotFriedman @utx0 also this refers specifically just to the relayer microservice going offline/crashing. we should really stop using the word validator to refer to anything relay related

**Comment by ElliotFriedman** [comment]
In my eyes, it would make more sense to just build in a mint function to cosmos where we have the admin key so that if a relayer drops and misses a TX, then we can just step in and mint tokens for that user. If we build a whole solution around retrying, it will require human input to figure out the TX that was dropped.

**Comment by musnit** [comment]
> In my eyes, it would make more sense to just build in a mint function to cosmos where we have the admin key so that if a relayer drops and misses a TX, then we can just step in and mint tokens for that user. If we build a whole solution around retrying, it will require human input to figure out the TX that was dropped.
> 
> In either case, we have to do human input, having an admin key and being able to mint seems simpler as we control all of the validators submitting oracle claims on sifchain.

don't think this would work due to legal reasons.

in terms of retrying/catchup, without any human input, i suggest something like:

`i think reliability should be fairly straightforward, basically we just need the relayer to do something like (example for direction cosmos -> ethereum):
start process
query ethereum to check most recent nonce from cosmos that has been confirmed on ethereum
query cosmos for all nonces from that nonce to the latest and start following new cosmos blocks
insert all in-between nonces into junius's new queue system and continue watching new blocks as normal
flush queue if needed
same for reverse direction
11:37
idk what luke is stressing about
11:37
we don't need fancy retries/synchronization
11:38
just make sure there is some way to restart and catchup
11:38
i suppose the above presumes we have a global nonce across all transactions, and that transactions are processed in order based on increasing nonce
11:38
not sure if we really have that or how much effort it would be to implement that, but seems like we've been basically building towards that anyway (edited) 
`

**Comment by ElliotFriedman** [comment]
Need two different solutions for this.
1. A script that takes transaction id's from ethereum and cosmos. It reads the transaction and submits the claim on the opposite chain for that transaction. This would require two scripts. One for sifchain to eth transactions, this would read the cosmos tx info, and submit prophecy claim based on this. For eth to sifchain transactions, this would read the eth transaction info and submit prophecy claim to sifchain.

2. The relayer itself stores the last block number that it has processed, when it is restarted, we can configure the last block number for it to read from. Probably won't go with this.

3. We add an ID to each tx that goes through the bridge. This ID is an increasing nonce. When a user locks or burns a token, that event gets an increasing nonce. When the relayer starts up, it can resume processing from the last nonce that it processed. Ways to do this, do sequential processing and put a lock in the relayer so that it cannot process transactions after transaction 5. Store onchain a list of what has been processed, this would be expensive.

**Comment by musnit** [comment]
> 2. The relayer itself stores the last block number that it has processed, when it is restarted, we can configure the last block number for it to read from. Probably won't go with this.
further context: this would not work if for example half a block of transactions is played but then the second half is missed. this would result in the first half being replayed twice.

> 3. We add an ID to each tx that goes through the bridge. This ID is an increasing nonce. When a user locks or burns a token, that event gets an increasing nonce. When the relayer starts up, it can resume processing from the last nonce that it processed. Ways to do this, do sequential processing and put a lock in the relayer so that it cannot process transactions after transaction 5. Store onchain a list of what has been processed, this would be expensive.
further context: the point of sequential processing in this solution is really for replay protection to make it easy for the relayer to know what transactions that it has missed and replay them. with sequential processing, it can easily tell this by checking the last nonce onchain and playing any transactions after that nonce. this does force the bridge to become ordered and process transactions in order. this kinda replay protection could also however be achieved by other means that do not necessarily force the bridge to become ordered, for example if instead the bridge was to store all transactions that have fully relayed and completed on-chain, then the on-chain logic could detect duplicate transactions and reject duplicates. this latter example would be much more gas expensive though.

**Comment by ElliotFriedman** [comment]
@musnit At this stage of where we are with development and timelines, it makes sense to go with the script solution. In the future, we could consider ordered transactions, however, nonces would have be maintained separately on each chain, so we only really can order in each direction, and not bidirectionally as there is an issue of communication and blocking. Additionally, the relayer would have to store the last nonce of the transaction that it proceesed from each chain, and if it went down, we would probably want the last nonce the relayer had read to be stored somewhere so that it can be easily recovered and pick up where it left off when it comes back online.

**Comment by ElliotFriedman** [comment]
Tx replay CLI has been merged to develop https://github.com/Sifchain/sifnode/pull/650/files
