### ISSUE TITLE
[Peggy] Implement SafeERC20 for token transfers in Peggy

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#330]
Token transfers in the bridge bank require a boolean to be returned, however some ERC20 implementations do not follow the EIP20 standard that requires they return a boolean. Because of this, we should use the openzeppelin implementation of safe ERC20 to transfer tokens. https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/SafeERC20.sol

**Comment by ElliotFriedman** [comment]
This is a critical issue and needs to be solved, but it should be a super straightforward and easy fix.

**Comment by utx0** [comment]
Hey @ElliotFriedman we got a ticket for this in asana?

**Comment by ElliotFriedman** [comment]
Yes, this is in the backlog of the peggy board.
