### ISSUE TITLE
[Peggy] decimals for cosmos or conversion to 10^18

### ISSUE THREAD

**Issue by ilyabukalov** [Sifchain/sifnode#342]
Currently Ethereum numbers (ERC-20 and ETH itself) and cosmos coins work correctly in terms of binary representation.
For example 100 ETH means 100 wei but not 100 Ether. The same happens with token. The numbers are processed correctly regardless of decimals based only on binary number representation. I believe it is correct behaviour and ERC-20 tokens decimals are purely "representation feature".

However: it still makes user confused. Highly visible it becomes with case of transferring ether. For example:

sifnodecli tx ethbridge burn $(sifnodecli keys show akasha -a) <ethereum receiver account> 100 ceth --ethereum-chain-id=5777 --from=akasha --yes

user expects to transfer 100 Ethers but not 100 wei.

The solution:
Either to implement and support decimals on cosmos side or at least to clarify it somehow in documentation and scripts. pioneers will never understand it correctly and we may have a lot of issues with that.

**Comment by utx0** [comment]
All values on the cosmo chain are in wei. Not sure what the ask is here?

**Comment by ilyabukalov** [comment]
> All values on the cosmo chain are in wei. Not sure what the ask is here?

based on your comment, since it is 100% confirmed and known that cosmos chain stores values in wei, based on that I believe this task is towards clear documentation. As first time user I was really confused about that fact ("cosmos chain stores values in wei"). And I marked it as "question" or "enhancement" but not a bug/issue.

**Comment by utx0** [comment]
At the end of the day cosmos is just a framework built on top of golang. So we can set it whatever way we want
