### ISSUE TITLE
[CLP] `sifnodecli q clp lp` to provide more details on assets in pool

### ISSUE THREAD

**Issue by utx0** [Sifchain/sifnode#380]
### Is your proposal related to a problem?

When querying via the cli with the following command: `sifnodecli q clp lp ceth $(sifnodecli keys show sif -a)`  only the value of y `liquidity_provider_units` is returned.

However I would also like to know how many nativeAmount and exteranlAmount I also have as part of this lp.

Eg:

```
[I] utx0@metta ~/C/s/sifnode (develop)> sifnodecli q clp lp ceth (sifnodecli keys show sif -a)
{
  "LiquidityProvider": {
    "asset": {
      "symbol": "ceth"
    },
    "liquidity_provider_units": "20000",
    "liquidity_provider_address": "sif1syavy2npfyt9tcncdtsdzf7kny9lh777yqc2nd"
  },
  "height": "100"
}

``` 

### Describe the solution you'd like

Extra output as follows;

```
[I] utx0@metta ~/C/s/sifnode (develop)> sifnodecli q clp lp ceth (sifnodecli keys show sif -a)
{
  "LiquidityProvider": {
    "asset": {
      "symbol": "ceth"
    },
    "native_asset_balance": "20000",
    "external_asset_balance": "20000",
    "liquidity_provider_units": "20000",
    "liquidity_provider_address": "sif1syavy2npfyt9tcncdtsdzf7kny9lh777yqc2nd"
  },
  "height": "100"
}

**Comment by utx0** [comment]
Same data should also be returned via the rest api too.

**Comment by Jedi2002** [comment]
@utx0  This can be added in ,
currently the liquidity provider does not store   the balance it has in a pool ,  only poolunits are required in all calcualtions . The current struct looks this 
type LiquidityProvider struct {
	Asset                                Asset                  `json:"asset"`
	LiquidityProviderUnits      sdk.Uint              `json:"liquidity_provider_units"`
	LiquidityProviderAddress sdk.AccAddress `json:"liquidity_provider_address"`
}

Adding this would require changes in all the handlers ,except createPool .

**Comment by AustinoBombino** [comment]
@Jedi2002 do you think we could just calculate their balance when the query is run?

**Comment by Jedi2002** [comment]
> @Jedi2002 do you think we could just calculate their balance when the query is run?

Yeah thats definitly doable

**Comment by AustinoBombino** [comment]
> > @Jedi2002 do you think we could just calculate their balance when the query is run?
> 
> Yeah thats definitly doable

Yeah we would need to do that. We can't track actual balances in the lp structures because their "balance" changes whenever swap fees are taken. That's why it's tracked with the units
