### ISSUE TITLE
[CLP] cli/rest return all pools info for a single key 

### ISSUE THREAD

**Issue by utx0** [Sifchain/sifnode#381]
### Is your proposal related to a problem?

Currently there is no way for a liquidity provider to get a a complete picture/output of all the lp there  assets in different pools in a single command. 

Only option is going via each pool eg: `sifnodecli q clp lp ceth $(sifnodecli keys show sif -a)`

### Describe the solution you'd like

A command like the following; 

`sifnodecli q clp pools (sifnodecli keys show sif -a)`

that returns all pools/lp info for all pools the key has assets in. 

### Additional context

We also need something like this in the rest API too.

**Comment by Jedi2002** [comment]
@utx0 we have a query 
sifnodecli q clp assets [lpAddress] 
Which returns a list of assets , the  [ lpAddress is contibuting to ] 

the rest counterpart for the above command is 
/clp/getAssets
