### ISSUE TITLE
[CLP] Return the pool/s onchain address as part of a query

### ISSUE THREAD

**Issue by utx0** [Sifchain/sifnode#382]
### Is your proposal related to a problem?

When preforming transaction like a swap on the lp's the tx will show the addresses used by the lp pools. To further increse the UX on the clp module it would be great to have the pool addresses returns as part of all pool cli/rest queries. 

Eg:

```
 utx0@metta ~/C/s/sifnode (develop)> sifnodecli q clp pools
{
  "Pools": [
    {
      "external_asset": {
        "symbol": "chot"
      },
      "native_asset_balance": "20003",
      "external_asset_balance": "20002",
      "pool_units": "20000"
    },
    {
      "external_asset": {
        "symbol": "clink"
      },
      "native_asset_balance": "29997",
      "external_asset_balance": "30007",
      "pool_units": "30000"
    }
  ],
  "height": "97"
}

```

### Describe the solution you'd like

```
 utx0@metta ~/C/s/sifnode (develop)> sifnodecli q clp pools
{
  "Pools": [
    {
      "external_asset": {
        "symbol": "chot"
      },
      "native_asset_balance": "20003",
      "external_asset_balance": "20002",
      "pool_units": "20000"
    },
    {
      "external_asset": {
        "symbol": "clink"
      },
      "native_asset_balance": "29997",
      "external_asset_balance": "30007",
      "pool_units": "30000"
    }
  ],
  "height": "97"
   "address: "sif1pjm228rsgwqf23arkx7lm9ypkyma7mzr3y2n85"
}
```

### Additional context

This will be handy for a number of end-user query uses. And help the general UX of the clp module

This should also be updated for both the cli and rest interfaces.

**Comment by Jedi2002** [comment]
We do not have adresses of individual pools right now. The design has been refacored to have one supplyaccount for the entire CLP module which stores the balance of all supported tokens .

We do have a module address, but that would be common for all the pools .

**Comment by utx0** [comment]
Yeah thats cool, just be great to return the clp address on the pools query. Otherwise you have to go digging for it.
