### ISSUE TITLE
[Bug install node on Mac] no valid credential sources for Terraform AWS Provider found.

### ISSUE THREAD

**Issue by mrworksome** [Sifchain/sifnode#441]
run all scripts on PyCharm IDE
First install all requirements and run ```rake "cluster:scaffold[merry-go-round,aws]"```
Then I try ```rake "cluster:deploy[merry-go-round,aws]"```
Then occurs instead
Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.

Please see https://registry.terraform.io/providers/hashicorp/aws
for more information about providing credentials.

Error: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors

and some problems with sifgen file or module

** Invoke keys:generate:mnemonic (first_time)
** Execute keys:generate:mnemonic
rake aborted!
Errno::ENOENT: No such file or directory - sifgen

Error in credential or not?

**Comment by utx0** [comment]
You need to have your aws `~/.aws/config` and `~/.aws/credentials` setup for terraform to work.
