### ISSUE TITLE
[CLP] Add extra parameter minimumReceivedAmount to prevent unexpected slippage. 

### ISSUE THREAD

**Issue by huangjosh** [Sifchain/sifnode#477]
### Is your proposal related to a problem?

When we doing swap from Token A to Token B, we can only specify the amount of Token A we will send, but we did not know how much Token B we will receive. 
In some corner cases, for example, when there are other users also swap Token A to Token B slightly earlier than us, and change the composition of the pool. We may receive the Token B much less than we expected.  This is dangerous and may cause user bankrupt.

### Describe the solution you'd like
The solution to the above question is simple. We should add a `minimumReceivedAmount` in the Cli API. This is the minimum amount of output token the user expect to receive. If the output token amount is falling below this `minimumReceivedAmount`, Sifchain should just cancel the transaction, and the user will still get back the original amount of input token he sent.

**Comment by utx0** [comment]
Hey @Jedi2002 / @AustinoBombino can you guys have a look at this request and see how we can work this into the clp solution?
