### ISSUE TITLE
Errno::ENOENT: No such file or directory - sifgen

### ISSUE THREAD

**Issue by ChanJuiHuang** [Sifchain/sifnode#501]
I run ```rake "keys:generate:mnemonic"``` from document.
But I encounter error.

Please help me, Thank you^^

![image](https://user-images.githubusercontent.com/12593365/104713077-559fa400-575e-11eb-833d-edaebf4d2335.png)

**Comment by utx0** [comment]
I have just merged a doco update that will fix this issue. Please review and let us know if this resolves your issue. Thanks
