### ISSUE TITLE
Sifnoded fails to continue syncing when daemon stopped and restarted in AWS pod

### ISSUE THREAD

**Issue by emperorjm** [Sifchain/sifnode#587]
I am using the sifchain aws kubernetes implementation and I need to make changes to the **config.toml** file to enable prometheus so that I can configure various metrics in dashboards within Grafana and also AWS CloudWatch to some extent seeing that prometheus integration is available there as well.

The only option I have right now is to update the **config.toml** within the sifnoded pod and I do this by connecting to the pod via a terminal, update the config file, stop and restart the service to reload the config. The following command is used to get shell access to the pod's container:

`kubectl -n sifnode --kubeconfig ./.live/sifchain-aws-merry-go-round/kubeconfig_sifchain-aws-merry-go-round exec --stdin --tty <add-name-of-pod-here> -- /bin/sh`

I would then run "**pgrep -a sifnoded**" and with the process id that's shown execute `kill -9 <pid-of-process>` to stop the process. I'd then start the process in the background using "**nohup sifnoded start**". Checking the pods logs I would get the following error:

```
dialing failed (attempts: 12): dial tcp 35.166.247.98:28004: i/o timeout module=pex addr=ca3341e335cba0bc8780d49986a6b49f11f804a9@35.166.247.98:28004
E[2021-01-26|22:29:44.737] dialing failed (attempts: 12): dial tcp 35.166.247.98:28006: i/o timeout module=pex addr=dd35505768be507af3c76f5a4ecdb272537e398f@35.166.247.98:28006
E[2021-01-26|22:29:44.737] dialing failed (attempts: 12): dial tcp 35.166.247.98:26656: i/o timeout module=pex addr=bd17ce50e4e07b5a7ffc661ed8156ac8096f57ce@35.166.247.98:26656
E[2021-01-26|22:29:44.737] dialing failed (attempts: 12): dial tcp 18.140.216.206:26656: i/o timeout module=pex addr=62a91f190ff08861f0602d146c39367b4be7589a@18.140.216.206:26656
E[2021-01-26|22:29:44.737] dialing failed (attempts: 12): dial tcp 35.166.247.98:26656: i/o timeout module=pex addr=ec03640d0dcb1160f8cf73c33c63b64a55c93906@35.166.247.98:26656
E[2021-01-26|22:29:44.737] dialing failed (attempts: 12): dial tcp 52.65.129.116:26656: i/o timeout module=pex addr=b77e0a8c16462f105669ad5966a10993cbf23205@52.65.129.116:26656
E[2021-01-26|22:29:44.737] dialing failed (attempts: 12): dial tcp 34.248.75.35:26656: i/o timeout module=pex addr=c4205fd291f3f8d163e0055d859e23ea1b31219a@34.248.75.35:26656
E[2021-01-26|22:29:44.737] dialing failed (attempts: 12): dial tcp 44.237.43.117:26656: i/o timeout module=pex addr=84d5b3f231b1eb001447d88b610368000d2f2eea@44.237.43.117:26656
E[2021-01-26|22:29:44.737] dialing failed (attempts: 12): dial tcp 35.166.247.98:28002: i/o timeout module=pex addr=f8f5d01fdc73e1b536084bbe42d0a81479f882b3@35.166.247.98:28002
E[2021-01-26|22:33:30.213] Stopping peer for error                      module=p2p peer="Peer{MConn{10.0.17.77:13208} 7b4d3e0fd0c7c0f275deb6ba02e4d3fdabffee4c in}" err=EOF
```

Not sure what to take from this error but it seems like there is some connection issue after the restart.

It would be great to be able to update various config files that are used by the sifnoded daemon and have them hot reloaded and if that's not possible, have an option to update the config and gracefully restart the service without it corrupting the database and not be able to continue synchronizing or signing transactions.

**Comment by utx0** [comment]
Once you restart the `sidnoded` process does the pod stay running?

**Comment by emperorjm** [comment]
I had to restart the **sifnoded** process a second time for the connection issue to go away. Not sure why that was the case and I did twice more and the same thing.
