### ISSUE TITLE
Error accessing remote module registry

### ISSUE THREAD

**Issue by alijnmerchant21** [Sifchain/sifnode#600]
**Describe the bug**
I am run into the error - "Error accessing remote module registry" when I hit the following command - 
rake "cluster:scaffold[merry-go-round,aws]"

For more detail on bug see the screen shot attached below.

**Bug Reproduction Steps**

1. Follow all the steps listed in sifnode/docs/chainOps/k8s.md
2. After all the prerequisites have been installed, scaffold a new cluster using 
rake "cluster:scaffold[merry-go-round,aws]" 

**Screenshots**
<img width="1454" alt="Screen Shot 2021-01-28 at 11 54 21 AM" src="https://user-images.githubusercontent.com/44069404/106182440-d03bdb00-61c4-11eb-8e22-220f4f94e116.png">

<img width="1345" alt="Screen Shot 2021-01-29 at 12 04 58 AM" src="https://user-images.githubusercontent.com/44069404/106183010-acc56000-61c5-11eb-8135-2071ac3a1cef.png">

**Other Helpful Bug Filing Info**
I have tried running the command as both - normal user and privileged user. (Root)

**Comment by alijnmerchant21** [comment]
The error was partially solved by updating owner of the files/directories of installed packages.

$sudo chown aliasgarmerchant /Users/aliasgarmerchant/go/pkg/…

**Comment by alijnmerchant21** [comment]
**Failed to query available provider packages**

<img width="1055" alt="Screen Shot 2021-01-31 at 12 32 42 PM" src="https://user-images.githubusercontent.com/44069404/106377554-be745680-63c3-11eb-9b46-7f5f61a3b6a3.png">


“Look specifically at the versions trying to be matched.”
a.	null >= 2.1.*
b.	template >= 2.1.*
c.	random >= 2.1.*
d.	aws >= 2.1.*
e.	kubernetes ~> 1.9 >= 1.11.1*
f.	local >= 1.4

Looking deeper into each of these links – 
E.g.: https://registry.terraform.io/v1/providers/hashicorp/null/versions

These versions do not exist.

<img width="1792" alt="Screen Shot 2021-01-31 at 12 48 47 PM" src="https://user-images.githubusercontent.com/44069404/106377581-05fae280-63c4-11eb-81fc-66c44d3a8ad5.png">

**Comment by utx0** [comment]
This looks like an issues getting the 3rd party terraform modules we are using from hashcorp... Maybe they had an outage or you have a network issues? Please re-try.
