### ISSUE TITLE
rake "keys:generate:mnemonic" 

### ISSUE THREAD

**Issue by realsteel85** [Sifchain/sifnode#623]
**Describe the bug**
When i runrake "keys:generate:mnemonic" i got an error

~/sifnode$ rake "keys:generate:mnemonic"
rake aborted!
Errno::ENOENT: No such file or directory - sifgen
/home/ubuntu/sifnode/deploy/rake/keys.rake:7:in ``'
/home/ubuntu/sifnode/deploy/rake/keys.rake:7:in `block (3 levels) in <top (required)>'
/usr/share/rubygems-integration/all/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => keys:generate:mnemonic

**Comment by utx0** [comment]
You havent setup `PATH=$HOME/go/bin:$PATH` in your shell
