### ISSUE TITLE
[Peggy] Only Saves to LevelDB on Second Startup

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#661]
**Describe the bug**
Currently, if you kill peggy the first time you have brought it up after running `start-integration-env.sh` while running with pkill ebrelayer || true, it will kill the relayer. If the relayer had no relayerdb file before, it won't create one, even if it says it saved some data to the database. Then, if you restart the relayer, and advance some blocks, it will create relayerdb and then start saving blocks. I cannot understand or figure out why this is the case. It could have to do with what happens when the relayer is killed like that. 

We need to investigate this and determine the root cause.

**Comment by ElliotFriedman** [comment]
Steps to reproduce:

1. Delete the relayerdb folder in your root directory of sifnode
2. Run start-integration-env.sh
3. Pull up the log files in another terminal by going to test/integration/vagrant/data/logs and catting the sifnoded and ebrelayer log files.
4. Advance blocks with the yarn advance script in the smart contract folder
5. Watch the ebrelayer log files get longer and see it tell you it is saving data to leveldb
6. Observe the root sifnode folder and see if the relayerdb directory pops up even as the ebrelayer logs tell you it is saving to the db.
7. run pkill ebrelayer || true
8. restart the relayer with this command run from the root directory of sifnode folder: 
```
source test/integration/vagrantenv.sh
pkill ebrelayer || true
nohup $TEST_INTEGRATION_DIR/sifchain_start_ebrelayer.sh < /dev/null > $EBRELAYER_LOG 2>&1 &
( tail -n +1 -F $EBRELAYER_LOG & ) | grep -m 1 "Started Ethereum websocket with provider"r 

```
9. Now, see if the relayerdb file is there, if it isn't, running the advanceblock script should put it there.

**Comment by ElliotFriedman** [comment]
I could be checking for this relayerdb directory in the wrong top level directory when I am getting this issue so it could just be a user error.

**Comment by banshee** [comment]
My guess is that you started ebrelayer from two different working directories.  start-integration-env.sh will always make smart-contracts the working directory when it launches ebrelayer, so the relayerdb/ directory should always be in smart-contracts for the integration tests.  If you have an relayerdb/ directory at the root, it wasn't created by the integration tests.

**Comment by banshee** [comment]
I think a good resolution would be to have ebrelayer take a --relayerdblocation flag to specify the location and not just use the working directory.

**Comment by ElliotFriedman** [comment]
That's looking like the likely issue is I am in the wrong directory when I restart it. I took a look to see if I could find the db somewhere outside the root directory, and low and behold, I found it in the smart-contracts directory as well. We could do what you suggested and give it a location, or just make sure our deployment scripts always run the same.

**Comment by ElliotFriedman** [comment]
Closing as I was starting the relayer in the wrong directory
