### ISSUE TITLE
[Peggy] Need to Remember Where to Restart on Cosmos

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#669]
**Describe the bug**
The current architecture of peggy when receiving transactions from cosmos does not remember the last block or transactions that were processed. We need to build a mechanism such that we remember where we left off if the relayer crashes or suddenly goes down.

This should also take care of:
- [ ] Handle peggy restart and cosmos event picking up from where it left off.

**Comment by intl-man** [comment]
Testing...seeing if this actually works!?
