### ISSUE TITLE
[Peggy] Sifchain to Ethereum Doesn't handle Eth nonce correctly

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#723]
**Describe the bug**
Currently, when peggy is spammed with 100 tx's at once going from sifchain to ethereum, a we have hit issues where 1-3 transactions do not add balance to the ethereum account. The root cause of this issue initially we believe was that one relayer did not hear a sifchain transaction as it was overloaded. We then bumped up the memory to 4GB on all relayers so they wouldn't miss anything. After this, we did the same 100 transactions and 3 of them didn't go through. We found this error message in the log repeated 3 times:
```
relayToEthereum.go:47: replacement transaction underpriced
```
The reason this error happened is due to not handling the nonce correctly. When the relayer gets the nonce from the function initRelayConfig, that function calls an inbuilt geth function `PendingNonceAt`, which should return us the proper nonce. The issue is, this function returns an incorrect nonce, and thus we send a replacement transaction instead of a new one with the same nonce as a previous transaction.

**Comment by ElliotFriedman** [comment]
Stack exchange question on this error: https://ethereum.stackexchange.com/questions/27256/error-replacement-transaction-underpriced

**Comment by musnit** [comment]
cool, sounds like can just be fixed by improving our relayer error handling and nonce synchronisation?

**Comment by ElliotFriedman** [comment]
Fix is here: https://github.com/Sifchain/sifnode/pull/711/files#

**Comment by utx0** [comment]
Closed by  https://github.com/Sifchain/sifnode/pull/711/
