### ISSUE TITLE
Some users running into very high gas prices when trying to execute a peg

### ISSUE THREAD

**Issue by caseyturnerarrington** [Sifchain/sifnode#789]
**Describe the bug**
Some users are running into very high gas prices when trying to execute a peg. This doesn't seem to be consistent.

**Bug Reproduction Steps**
When executing a peg transaction, some gas prices are upwards of $3k?

**Screenshots**
<img width="1276" alt="Screen Shot 2021-02-19 at 7 01 53 AM" src="https://user-images.githubusercontent.com/45978818/108521369-a80e3c00-7299-11eb-8696-e7677fb9153a.png">

**Comment by 59023g** [comment]
Is this on Approve? or Spend?

**Comment by 59023g** [comment]
@banshee pointed out we do not set gas limit on `burn()`
