### ISSUE TITLE
Users not able to see their liquidity pools

### ISSUE THREAD

**Issue by caseyturnerarrington** [Sifchain/sifnode#794]
**Describe the bug**
After a user addes liquidity to a pool, those pools are not displaying in their list of liquidity pools.

**Bug Reproduction Steps**
- Add liquidity to any pool.
- Successfully finish the adding of liquidty transaction.
- Now navigate to 'Pool'.
- The pool that the user just added liquidity too should be displayed in the You pool lists.

**Screenshots**
![Screen Shot 2021-02-19 at 10 10 10 AM](https://user-images.githubusercontent.com/45978818/108543968-ce40d580-72b3-11eb-9293-48fd3c204c75.png)

**Additional context**
- This seems to be a new bug as of today 02/19/21
- It does not seem to be specific so specific pools as Taylor has liquidity in ALL pools and NONE are displaying for him.

**Comment by 59023g** [comment]
Very peculiar. And is working now. Wonder if has something to do with end point load capacities? 

I do see, on our end, it's call intensive, meaning there's one call to `getPools` then `<address>` then `getAssets`  then one call to `getLiquidityProvider` per pool user has about once per 5 seconds. So for Taylor, he's making about 55 calls per 5 seconds. Some of which don't return until the next iteration has already started. 

But it also effects people with 2 pools...

I think UI should try to make this more efficient and add a loader. But I wonder if it's a network load issue?  

@utx0 @intl-man 

<img width="317" alt="Screen Shot 2021-02-19 at 3 43 29 PM" src="https://user-images.githubusercontent.com/5235538/108565602-91340d80-72ca-11eb-8251-9ab9f0be6a01.png">

**Comment by caseyturnerarrington** [comment]
Closing this.
