### ISSUE TITLE
Feature: Guidance on Liquidity Pool Ratio

### ISSUE THREAD

**Issue by caseyturnerarrington** [Sifchain/sifnode#901]
**To do:**
- A toggleable feature that "suggests" optimal ratio when depositing value to liquidity pool.

**Here is what I am thinking for this:**
- We implement a toggle that allows a user to change from asymmetrical to symmetrical pooling. 
- If asymmetrical (which it will default to) is turned on, pooling will work the exact way that it works right now. 
- If symmetrical is turned on, then we will auto-determine the 'other' amount for them. Meaning, if they input the first input field, we will auto-determine the 2nd input field based upon the value that is currently in the pool (and same if the user decides to edit the 2nd input field). 
- The goal would be to auto-calculate the 'other' input field for the user as so the pool token prices themselves are not affected (because the increments in the new addition to the pool are at a rate that it will keep the pool prices the exact same).
- For the placement of this toggle, I think we should put it right above the first displayed balance on the right-hand side. Just be sure to adjust the spacing between it and the 'Add Liquidity' header so it looks natural and not squished.

**Comment by thomasdavis** [comment]
PR ready for review -> https://github.com/Sifchain/sifnode/pull/663
