### ISSUE TITLE
Implement Prettier code standards across whole UI codebase

### ISSUE THREAD

**Issue by caseyturnerarrington** [Sifchain/sifnode#903]
"I think whatever it is it needs to be automatic and it needs to be universal." - Rudi

**Comment by thomasdavis** [comment]
WIP PR -> https://github.com/Sifchain/sifnode/pull/867

**Comment by caseyturnerarrington** [comment]
@59023g @thomasdavis is this considered done?

**Comment by 59023g** [comment]
Done
