### ISSUE TITLE
Incorrect TVL Stats

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#921]
Currently, the TVL stats on the dex page is incorrect. From what I can see, it includes all of the token value that is locked in the bridge bank, however, it does not include the value of the ether that is locked in the bridge bank as well.

How to replicate this issue:
Go to the bridgebank etherscan link and view all of the value of the crypto locked in it: https://etherscan.io/address/0xb5f54ac4466f5ce7e0d8a5cb9fe7b8c0f35b7ba8

After that, go to our DEX and look at the TVL number. If you divide that by 2, you will get a value that only represents the value of the tokens and not ether locked in the bridgebank.

https://dex.sifchain.finance/#/stats

**Comment by caseyturnerarrington** [comment]
@ElliotFriedman @nikohosn our TVL that we display in the DEX is:
1) Pool Depth across every pool
2) x2
= TVL

I feel like this is correct. I would chat with @AustinoBombino if you think that this should be adjusted.

**Comment by ElliotFriedman** [comment]
Formula for this page should look like this:

Pool depth = rowan amount locked in pools
eth & tokens value locked = TVL in eth smart contract that has been pegged to sifchain

Pool depth + eth & tokens value locked 
    = TVL

@nikohosn @AustinoBombino

**Comment by ElliotFriedman** [comment]
@AustinoBombino I think it boils down to how we measure things. If we measure by total value pegged into the system, or if we measure things by total value pooled on sifchain.

**Comment by AustinoBombino** [comment]
@ElliotFriedman  Yeah, totally agree. Just need to nail down which we want and make it clear to the user what that is.

**Comment by caseyturnerarrington** [comment]
We are calculating this correctly. Total locked-in pools. Closing ticket.
