### ISSUE TITLE
Add feature to integration test environment to allow using geth (ropsten, private geth network etc) instead of ganache for local test

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#963]
Comment:

There are still a couple details to clean up, and it got kicked out of being the top item on my priority list. We can run test_eth_transfers against a local geth, and we can run selected tests against testnets (sandpit, swing-set).

**Comment by banshee** [comment]
Duplicate of https://github.com/Sifchain/issues/issues/92
