### ISSUE TITLE
Instead of burning Ceth on Lock or Burn TX's, transfer to an account.

### ISSUE THREAD

**Issue by ElliotFriedman** [Sifchain/sifnode#968]
Currently, when a user submits a lock or burn transaction on sifchain to move their funds across the bridge, the ceth amount in that transaction gets sent to a cosmos module. We need a function in cosmos that anyone can call that pays out all ceth balance of that cosmos module to a hardcoded sifchain address that we control. This will allow us to retrieve all locked ceth. We can then unpeg that ceth and then use that for funding the relayers again. With this code change, we need a script to call this function to get us our ceth we are currently owed.

Additionally, we want all ceth that gets burned for lock and burn fees immediately transferred to a sifchain account that we control so that there is no manual process to retrieve the ceth.

**Comment by pandaring2you** [comment]
After this is pushed, will need to be tested. Then devops will need to run scripts to update env variables to allow exec to withdraw ceth.
