### ISSUE TITLE
Revise Jailing params

### ISSUE THREAD

**Issue by utx0** [Sifchain/sifnode#996]
Community is asking for changes to the jail params. This will need to be reviewed due to possible issues with cosmos 0.39 and might have to wait until we upgrade to 0.4x 

```
⁃ SignedBlocksWindow: 5000 is a very good round number. 
 ⁃ MinSignedPerWindow: "0.050000000000000000"
 ⁃ SlashFractionDowntime: 0.000100000000000000 which equates to 0.01% as persons have lost a good number of tokens within the past 4 weeks with Maj Reg destroying 11% of their delegators tokens after being jailed 11 times.
```

**Comment by westaking** [comment]
BlockTime : 5.65s
SignedBlocksWindow: 5000
MinSignedPerWindow: 0.05

SignedBlocksWindow * ( 1 - MinSignedPerWindow ) * BlockTime 
5000 * ( 1 - 0.05 ) * 5.65s = 26837.5s (7.454861h)

The 7.5h downtime allowance is still not enough.
Validators need enough time to overcome failures in unexpected situations.

Let's take an example.

There is a validator service provider with 2 operators working.
It's tight if they work in shifts, but they can cover all of them 24/7/365.

But suppose one of them had an unexpected accident.
Temporarily, the other one should manage the validator nodes.
But one person cannot cover all the time.
As a person, fatigue can accumulate and he may not be aware of the alert system.

If a failure occurs while he is sleeping for about 8 hours, the validator is slashing.
We live in a global era and all operators live in different time zones.
Server failure situations vary, and there should be enough time to cover them.

Therefore, it is suggested to allow 15h or more downtime like cosmos.

Also, SlashFractionDowntime: 0.0001 is too low. 
If it is too low, there is a lack of responsibility.
This will also be 0.001 (0.1%) like cosmos.

**Comment by creamjun** [comment]
'This will also be 0.001 (0.1%) like cosmos.'
-> This also suggests 0.001 (0.1%) like cosmos.

**Comment by jkbrooks** [comment]
@caseyturnerarrington please get this into the sprint next week

**Comment by caseyturnerarrington** [comment]
@jkbrooks we had a meeting on this today. It will be in on Monday.

**Comment by caseyturnerarrington** [comment]
Decision:
⁃ SignedBlocksWindow: 5000
⁃ MinSignedPerWindow: 0.050000000000000000
⁃ SlashFractionDowntime: 0.000100000000000000

**Comment by westaking** [comment]
> Decision:
> ⁃ SignedBlocksWindow: 5000
> ⁃ MinSignedPerWindow: 0.050000000000000000
> ⁃ SlashFractionDowntime: 0.000100000000000000

What was the basis for this decision?

**Comment by jkbrooks** [comment]
@caseyturnerarrington yea I'd love to know how we got to this decision as well.  It looks like we did everything requested except update SlashFractionDowntime but why not make it 0.001?

**Comment by caseyturnerarrington** [comment]
Reason behind these numbers:
- We are wanting to strike a balance between a) responsibility and b) forgiveness as our product and our processed take form and mature. 

For this reason, we decided that ~7.5 hours of downtime is a sufficient amount of time to get a node back up and running in the case something goes down. We also decided to be a bit liberal on our SlashFractionDowntime as, again, we are a network that is still growing and evolving at this point and therefore need to be a bit more lenient when it comes to this. 

At this point, we think this is a good balance. Again, we are in the younger stages of our network (only 66 node validators at the moment). So we want our nodes to be responsible for remaining up, but forgiving in case extenuating circumstances occur.

**Comment by jkbrooks** [comment]
Thanks @caseyturnerarrington please link to the PR corresponding to this issue.  Alternatively, if you link to this issue in the PR, Github will create a link to the PR here automatically - https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by caseyturnerarrington** [comment]
@intl-man Can you link the corresponding PR to this ticket please?

**Comment by intl-man** [comment]
@caseyturnerarrington PR: https://github.com/Sifchain/sifnode/pull/1129
